-- ⚠️ BU KODU SUPABASE SQL EDITOR'DE CALISTIRIN ⚠️

-- 1. Tabloları Temizle (Eski Türkçe verileri sil)
TRUNCATE TABLE categories CASCADE;
ALTER TABLE categories ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 2. Ana Kategorileri İngilizce Ekle
INSERT INTO categories (id, title, slug, icon, parent_id) VALUES
(1, 'Computing', 'computing', 'Monitor', NULL),
(2, 'Phones & Accessories', 'phones', 'Smartphone', NULL),
(3, 'Gaming & Consoles', 'gaming', 'Gamepad2', NULL),
(4, 'TV & Audio', 'audio-video', 'Tv', NULL),
(5, 'Cameras & Drones', 'cameras', 'Camera', NULL),
(6, 'Smart Home', 'smart-home', 'Zap', NULL);

-- 3. Sayacı Güncelle
SELECT setval(pg_get_serial_sequence('categories', 'id'), (SELECT MAX(id) FROM categories));

-- 4. Alt Kategorileri İngilizce Ekle
INSERT INTO categories (title, slug, icon, parent_id) VALUES
('Laptops', 'laptops', 'Laptop', 1),
('Desktops', 'desktops', 'Monitor', 1),
('Tablets', 'tablets', 'Tablet', 1),
('Components', 'components', 'Cpu', 1),
('Networking', 'networking', 'Wifi', 1),

('Smartphones', 'smartphones', 'Smartphone', 2),
('Smart Watches', 'wearables', 'Watch', 2),
('Cases & Protection', 'cases', 'Shield', 2),

('Consoles', 'consoles', 'Gamepad', 3),
('Video Games', 'games', 'Disc', 3),
('Accessories', 'gaming-accessories', 'Keyboard', 3),

('Televisions', 'tvs', 'Tv', 4),
('Headphones', 'headphones', 'Headphones', 4),
('Speakers', 'speakers', 'Speaker', 4),

('Digital Cameras', 'digital-cameras', 'Camera', 5),
('Drones', 'drones', 'Plane', 5),

('Robot Vacuums', 'robot-vacuums', 'Bot', 6),
('Smart Lighting', 'smart-lighting', 'Zap', 6);