-- BU KODU SUPABASE SQL EDITOR'DE CALISTIRIN --

-- 1. ADS Tablosuna Elektronik Sütunlarını Ekle
ALTER TABLE ads ADD COLUMN IF NOT EXISTS brand text;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS model text;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS processor text;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS ram text;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS screen_size text;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS gpu_capacity text;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS resolution text;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS ssd_capacity text;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS technical_specs jsonb;

-- 2. Kategorileri Sıfırla ve Yeniden Kur
TRUNCATE TABLE categories CASCADE;
ALTER TABLE categories ALTER COLUMN id SET GENERATED BY DEFAULT;

INSERT INTO categories (id, title, slug, icon, parent_id) VALUES
(1, 'Bilgisayar', 'bilgisayar', 'Monitor', NULL),
(2, 'Telefon & Aksesuar', 'telefon', 'Smartphone', NULL),
(3, 'Oyun & Konsol', 'oyun', 'Gamepad2', NULL),
(4, 'TV & Ses', 'tv-ses', 'Tv', NULL),
(5, 'Fotoğraf & Kamera', 'kamera', 'Camera', NULL),
(6, 'Akıllı Ev & Yaşam', 'akilli-ev', 'Zap', NULL);

-- Sayacı güncelle
SELECT setval(pg_get_serial_sequence('categories', 'id'), (SELECT MAX(id) FROM categories));

-- Alt Kategoriler
INSERT INTO categories (title, slug, icon, parent_id) VALUES
('Laptop / Notebook', 'laptop', 'Laptop', 1),
('Masaüstü Bilgisayar', 'masaustu', 'Monitor', 1),
('Tablet', 'tablet', 'Tablet', 1),
('Oyuncu Ekipmanları', 'oyuncu-ekipman', 'Keyboard', 1),
('PC Bileşenleri', 'bilesenler', 'Cpu', 1),
('Cep Telefonu', 'cep-telefonu', 'Smartphone', 2),
('Akıllı Saat', 'giyilebilir', 'Watch', 2),
('Kılıf & Aksesuar', 'kilif', 'Shield', 2),
('Oyun Konsolları', 'konsol', 'Gamepad', 3),
('Video Oyunları', 'video-oyun', 'Disc', 3),
('Televizyon', 'televizyon', 'Tv', 4),
('Kulaklık', 'kulaklik', 'Headphones', 4),
('Dijital Kamera', 'dslr', 'Camera', 5),
('Drone', 'drone', 'Plane', 5),
('Robot Süpürge', 'robot-supurge', 'Bot', 6);