-- BU KODU SUPABASE SQL EDITOR EKRANINDA ÇALIŞTIRIN --

-- 1. Kategorileri Temizle ve ID Ayarını Düzelt
TRUNCATE TABLE categories CASCADE;
ALTER TABLE categories ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 2. Ana Teknoloji Kategorileri
INSERT INTO categories (id, title, slug, icon, parent_id) VALUES
(1, 'Bilgisayar', 'bilgisayar', 'Monitor', NULL),
(2, 'Telefon & Aksesuar', 'telefon', 'Smartphone', NULL),
(3, 'Oyun & Konsol', 'oyun', 'Gamepad2', NULL),
(4, 'TV & Ses', 'tv-ses', 'Tv', NULL),
(5, 'Fotoğraf & Kamera', 'kamera', 'Camera', NULL),
(6, 'Akıllı Ev & Yaşam', 'akilli-ev', 'Zap', NULL);

-- 3. Sayacı Güncelle
SELECT setval(pg_get_serial_sequence('categories', 'id'), (SELECT MAX(id) FROM categories));

-- 4. Bilgisayar Alt Kategorileri
INSERT INTO categories (title, slug, icon, parent_id) VALUES
('Laptop / Notebook', 'laptop', 'Laptop', 1),
('Masaüstü Bilgisayar', 'masaustu', 'Monitor', 1),
('Tablet', 'tablet', 'Tablet', 1),
('Oyuncu Ekipmanları', 'oyuncu-ekipman', 'Keyboard', 1),
('PC Bileşenleri (Donanım)', 'bilesenler', 'Cpu', 1),
('Ağ & Modem', 'network', 'Wifi', 1);

-- 5. Telefon Alt Kategorileri
INSERT INTO categories (title, slug, icon, parent_id) VALUES
('Cep Telefonu', 'cep-telefonu', 'Smartphone', 2),
('Akıllı Saat & Bileklik', 'giyilebilir', 'Watch', 2),
('Kılıf & Ekran Koruyucu', 'kilif', 'Shield', 2),
('Şarj & Kablo', 'sarj', 'Zap', 2);

-- 6. Oyun & Konsol
INSERT INTO categories (title, slug, icon, parent_id) VALUES
('Oyun Konsolları', 'konsol', 'Gamepad', 3),
('Video Oyunları', 'video-oyun', 'Disc', 3),
('Joystick & Gamepad', 'gamepad', 'Gamepad2', 3);

-- 7. Diğer Kategoriler
INSERT INTO categories (title, slug, icon, parent_id) VALUES
('Televizyon', 'televizyon', 'Tv', 4),
('Kulaklık', 'kulaklik', 'Headphones', 4),
('Bluetooth Hoparlör', 'hoparlor', 'Speaker', 4),
('Dijital Kamera', 'dslr', 'Camera', 5),
('Drone', 'drone', 'Plane', 5),
('Robot Süpürge', 'robot-supurge', 'Bot', 6);