const fs = require("fs");
const path = require("path");

const colors = {
  reset: "\x1b[0m",
  green: "\x1b[32m",
  blue: "\x1b[34m",
  yellow: "\x1b[33m",
  bold: "\x1b[1m",
};

console.log(
  colors.blue +
    colors.bold +
    "\n🚀  TECH-MARKETPLACE (FINAL DÜZELTME) BAŞLATILIYOR...\n" +
    colors.reset,
);

// ---------------------------------------------------------
// 1. SQL SEED (Kategoriler & Özellikler)
// ---------------------------------------------------------
const sqlContent = `
-- BU KODU SUPABASE SQL EDITOR EKRANINDA ÇALIŞTIRIN --

-- 1. Kategorileri Temizle ve ID Ayarını Düzelt
TRUNCATE TABLE categories CASCADE;
ALTER TABLE categories ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 2. Ana Teknoloji Kategorileri
INSERT INTO categories (id, title, slug, icon, parent_id) VALUES
(1, 'Bilgisayar', 'bilgisayar', 'Monitor', NULL),
(2, 'Telefon & Aksesuar', 'telefon', 'Smartphone', NULL),
(3, 'Oyun & Konsol', 'oyun', 'Gamepad2', NULL),
(4, 'TV & Ses', 'tv-ses', 'Tv', NULL),
(5, 'Fotoğraf & Kamera', 'kamera', 'Camera', NULL),
(6, 'Akıllı Ev & Yaşam', 'akilli-ev', 'Zap', NULL);

-- 3. Sayacı Güncelle
SELECT setval(pg_get_serial_sequence('categories', 'id'), (SELECT MAX(id) FROM categories));

-- 4. Bilgisayar Alt Kategorileri
INSERT INTO categories (title, slug, icon, parent_id) VALUES
('Laptop / Notebook', 'laptop', 'Laptop', 1),
('Masaüstü Bilgisayar', 'masaustu', 'Monitor', 1),
('Tablet', 'tablet', 'Tablet', 1),
('Oyuncu Ekipmanları', 'oyuncu-ekipman', 'Keyboard', 1),
('PC Bileşenleri (Donanım)', 'bilesenler', 'Cpu', 1),
('Ağ & Modem', 'network', 'Wifi', 1);

-- 5. Telefon Alt Kategorileri
INSERT INTO categories (title, slug, icon, parent_id) VALUES
('Cep Telefonu', 'cep-telefonu', 'Smartphone', 2),
('Akıllı Saat & Bileklik', 'giyilebilir', 'Watch', 2),
('Kılıf & Ekran Koruyucu', 'kilif', 'Shield', 2),
('Şarj & Kablo', 'sarj', 'Zap', 2);

-- 6. Oyun & Konsol
INSERT INTO categories (title, slug, icon, parent_id) VALUES
('Oyun Konsolları', 'konsol', 'Gamepad', 3),
('Video Oyunları', 'video-oyun', 'Disc', 3),
('Joystick & Gamepad', 'gamepad', 'Gamepad2', 3);

-- 7. Diğer Kategoriler
INSERT INTO categories (title, slug, icon, parent_id) VALUES
('Televizyon', 'televizyon', 'Tv', 4),
('Kulaklık', 'kulaklik', 'Headphones', 4),
('Bluetooth Hoparlör', 'hoparlor', 'Speaker', 4),
('Dijital Kamera', 'dslr', 'Camera', 5),
('Drone', 'drone', 'Plane', 5),
('Robot Süpürge', 'robot-supurge', 'Bot', 6);
`;

// ---------------------------------------------------------
// 2. FRONTEND DATA (lib/data.ts)
// ---------------------------------------------------------
const dataTsContent = `
import { Monitor, Smartphone, Camera, Tv, Gamepad2, Plug, Cpu, Laptop, Watch, Headphones, Speaker, Shield, Zap, Wifi, Disc, Keyboard, Mouse, Bot, Plane } from 'lucide-react';

export const categories = [
  {
    id: 'bilgisayar', title: 'Bilgisayar', icon: 'Monitor', slug: 'bilgisayar',
    subs: [
      { id: 'laptop', title: 'Laptop / Notebook', slug: 'laptop', icon: 'Laptop' },
      { id: 'masaustu', title: 'Masaüstü PC', slug: 'masaustu', icon: 'Monitor' },
      { id: 'tablet', title: 'Tablet', slug: 'tablet', icon: 'Tablet' },
      { id: 'bilesenler', title: 'PC Bileşenleri', slug: 'bilesenler', icon: 'Cpu' },
      { id: 'ekipman', title: 'Oyuncu Ekipmanları', slug: 'oyuncu-ekipman', icon: 'Keyboard' }
    ]
  },
  {
    id: 'telefon', title: 'Telefon & Aksesuar', icon: 'Smartphone', slug: 'telefon',
    subs: [
      { id: 'cep', title: 'Cep Telefonu', slug: 'cep-telefonu', icon: 'Smartphone' },
      { id: 'giyilebilir', title: 'Akıllı Saat', slug: 'giyilebilir', icon: 'Watch' },
      { id: 'kilif', title: 'Kılıf & Koruyucu', slug: 'kilif', icon: 'Shield' }
    ]
  },
  {
    id: 'oyun', title: 'Oyun & Konsol', icon: 'Gamepad2', slug: 'oyun',
    subs: [
      { id: 'konsol', title: 'Oyun Konsolları', slug: 'konsol', icon: 'Gamepad2' },
      { id: 'oyunlar', title: 'Oyunlar', slug: 'video-oyun', icon: 'Disc' }
    ]
  },
  {
    id: 'tv-ses', title: 'TV & Ses', icon: 'Tv', slug: 'tv-ses',
    subs: [
      { id: 'tv', title: 'Televizyon', slug: 'televizyon', icon: 'Tv' },
      { id: 'kulaklik', title: 'Kulaklık', slug: 'kulaklik', icon: 'Headphones' },
      { id: 'hoparlor', title: 'Hoparlör', slug: 'hoparlor', icon: 'Speaker' }
    ]
  },
  {
    id: 'kamera', title: 'Kamera', icon: 'Camera', slug: 'kamera',
    subs: [
      { id: 'dslr', title: 'Dijital Kamera', slug: 'dslr', icon: 'Camera' },
      { id: 'drone', title: 'Drone', slug: 'drone', icon: 'Plane' }
    ]
  },
  {
    id: 'akilli-ev', title: 'Akıllı Ev', icon: 'Zap', slug: 'akilli-ev',
    subs: [
        { id: 'robot', title: 'Robot Süpürge', slug: 'robot-supurge', icon: 'Bot' }
    ]
  }
];

export const cities = ['İstanbul', 'Ankara', 'İzmir', 'Antalya', 'Bursa', 'Kocaeli', 'Adana', 'Eskişehir'];
`;

// ---------------------------------------------------------
// 3. WIZARD HIERARCHY (lib/hierarchyData.ts)
// ---------------------------------------------------------
const hierarchyDataContent = `
import { Monitor, Smartphone, Camera, Tv, Gamepad2, Plug } from 'lucide-react';

export type CategoryNode = {
  id: string;
  title: string;
  slug: string;
  icon?: any;
  subs?: CategoryNode[];
  isDynamic?: boolean;
  dynamicType?: 'computer' | 'phone';
};

export const categoryTree: CategoryNode[] = [
  {
    id: 'bilgisayar', title: 'Bilgisayar', icon: 'Monitor', slug: 'bilgisayar',
    subs: [
      { id: 'laptop', title: 'Laptop', slug: 'laptop', isDynamic: true, dynamicType: 'computer' },
      { id: 'masaustu', title: 'Masaüstü', slug: 'masaustu' },
      { id: 'tablet', title: 'Tablet', slug: 'tablet' },
      { id: 'bilesenler', title: 'Bileşenler', slug: 'bilesenler' }
    ]
  },
  {
    id: 'telefon', title: 'Telefon', icon: 'Smartphone', slug: 'telefon',
    subs: [
      { id: 'cep-telefonu', title: 'Cep Telefonu', slug: 'cep-telefonu', isDynamic: true, dynamicType: 'phone' },
      { id: 'aksesuar', title: 'Aksesuar', slug: 'telefon-aksesuar' }
    ]
  },
  {
    id: 'tv-ses', title: 'TV & Ses', icon: 'Tv', slug: 'tv-ses',
    subs: [
      { id: 'televizyon', title: 'Televizyon', slug: 'televizyon' },
      { id: 'ses-sistemi', title: 'Ses Sistemi', slug: 'ses-sistemi' }
    ]
  },
  {
    id: 'kamera', title: 'Kamera', icon: 'Camera', slug: 'kamera',
    subs: [
      { id: 'fotograf', title: 'Fotoğraf Makinesi', slug: 'fotograf-makinesi' },
      { id: 'drone', title: 'Drone', slug: 'drone' }
    ]
  },
  {
    id: 'oyun', title: 'Oyun & Konsol', icon: 'Gamepad2', slug: 'oyun',
    subs: [
      { id: 'konsol', title: 'Oyun Konsolu', slug: 'konsol' }
    ]
  }
];

// Araba verisi boşaltıldı
export const carHierarchy: Record<string, Record<string, string[]>> = {};

export const computerBrands = [
  "Apple", "Asus", "Lenovo", "HP", "Dell", "Acer", "MSI", "Monster", "Casper", "Huawei", "Samsung", "Toshiba", "Microsoft"
];

export const phoneBrands = [
  "Apple", "Samsung", "Xiaomi", "Huawei", "Oppo", "Vivo", "Realme", "Honor", "General Mobile", "Tecno"
];
`;

// ---------------------------------------------------------
// 4. CLEAN SCHEMAS (lib/schemas.ts)
// ---------------------------------------------------------
const schemaContent = `
import { z } from 'zod';

export const adSchema = z.object({
  title: z.string().min(5, "Başlık en az 5 karakter olmalıdır").max(100, "Başlık çok uzun"),
  description: z.string().min(10, "Açıklama en az 10 karakter olmalıdır"),
  price: z.number({ invalid_type_error: "Geçerli bir fiyat giriniz" }).min(0, "Fiyat 0'dan küçük olamaz"),
  currency: z.enum(['TL', 'USD', 'EUR', 'GBP']),
  city: z.string().min(1, "İl seçimi zorunludur"),
  district: z.string().min(1, "İlçe seçimi zorunludur"),
  category: z.string().min(1, "Kategori seçimi zorunludur"),
  image: z.string().nullable().optional(),
  images: z.array(z.string()).optional(),

  // Elektronik Özellikleri
  brand: z.string().optional().nullable(),
  model: z.string().optional().nullable(),
  processor: z.string().optional().nullable(),
  ram: z.string().optional().nullable(),
  screen_size: z.string().optional().nullable(),
  gpu_capacity: z.string().optional().nullable(),
  resolution: z.string().optional().nullable(),
  ssd_capacity: z.string().optional().nullable(),

  // Eski alanlar (Hata önlemek için optional tutuldu ama arayüzden kaldırılacak)
  year: z.any().optional().nullable(),
  km: z.any().optional().nullable(),
  m2: z.any().optional().nullable(),
  room: z.any().optional().nullable(),

  technical_specs: z.any().optional().nullable()
});

export type AdFormValues = z.infer<typeof adSchema>;
`;

// ---------------------------------------------------------
// 5. YENİLENMİŞ FİLTRE SIDEBAR (components/FilterSidebar.tsx)
// ---------------------------------------------------------
const filterSidebarContent = `
"use client";
import React, { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Filter, RotateCcw, ChevronDown, ChevronUp, Search, Cpu, Monitor, HardDrive } from 'lucide-react';
import { computerBrands, phoneBrands } from '@/lib/hierarchyData';
import { processors, ramOptions, screenSizes, gpuCapacities, ssdCapacities } from '@/lib/computerData';

export default function FilterSidebar() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [filters, setFilters] = useState({});
  const [expanded, setExpanded] = useState({
      brand: true, specs: true, price: true
  });

  useEffect(() => {
    const newFilters = {};
    searchParams.forEach((value, key) => { newFilters[key] = value; });
    setFilters(newFilters);
  }, [searchParams]);

  const updateFilter = (key, value) => {
      setFilters((prev) => {
          const next = { ...prev, [key]: value };
          if (!value) delete next[key];
          return next;
      });
  };

  const applyFilters = () => {
    const params = new URLSearchParams();
    Object.entries(filters).forEach(([key, value]) => {
        if (value) params.set(key, value);
    });
    params.set('showResults', 'true');
    router.push(\`/search?\${params.toString()}\`);
  };

  const clearFilters = () => {
    router.push('/search');
  };

  const toggle = (id) => setExpanded(prev => ({ ...prev, [id]: !prev[id] }));

  // Kategoriye göre marka listesi
  const cat = filters.category || '';
  let activeBrands = computerBrands;
  if (cat.includes('telefon') || cat.includes('cep')) activeBrands = phoneBrands;

  const FilterSection = ({ id, title, icon: Icon, children }) => (
      <div className="border-b border-gray-100 py-4 last:border-0">
          <button onClick={() => toggle(id)} className="flex items-center justify-between w-full text-left mb-2 group">
              <span className="text-xs font-bold text-slate-700 uppercase tracking-wide flex items-center gap-2 group-hover:text-blue-600 transition-colors">
                  {Icon && <Icon size={14} className="text-slate-400 group-hover:text-blue-500"/>} {title}
              </span>
              {expanded[id] ? <ChevronUp size={14} className="text-gray-400"/> : <ChevronDown size={14} className="text-gray-400"/>}
          </button>
          {expanded[id] && <div className="space-y-3 pt-2 animate-in slide-in-from-top-1">{children}</div>}
      </div>
  );

  return (
    <div className="bg-white border border-gray-200 rounded-xl shadow-sm p-5 sticky top-24">

      <div className="mb-6 bg-indigo-50/50 p-4 rounded-xl border border-indigo-100">
        <h3 className="font-bold text-indigo-900 text-sm mb-3 flex items-center gap-2">
            <Filter size={16} /> Filtrele
        </h3>
        <button onClick={applyFilters} className="w-full bg-indigo-600 text-white text-sm font-bold py-2.5 rounded-lg hover:bg-indigo-700 transition-all shadow-sm flex items-center justify-center gap-2">
            <Search size={16} /> Sonuçları Göster
        </button>
        <button onClick={clearFilters} className="w-full text-center text-xs text-slate-500 hover:text-red-600 mt-2 flex items-center justify-center gap-1 font-medium transition-colors">
            <RotateCcw size={12}/> Temizle
        </button>
      </div>

      <FilterSection id="price" title="Fiyat Aralığı">
          <div className="flex gap-2 items-center">
              <input type="number" placeholder="Min TL" value={filters.minPrice || ''} onChange={(e) => updateFilter('minPrice', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-3 outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500" />
              <span className="text-gray-400">-</span>
              <input type="number" placeholder="Max TL" value={filters.maxPrice || ''} onChange={(e) => updateFilter('maxPrice', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-3 outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500" />
          </div>
      </FilterSection>

      <FilterSection id="brand" title="Marka">
          <select value={filters.brand || ''} onChange={(e) => updateFilter('brand', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-2 focus:border-indigo-500 outline-none bg-white">
              <option value="">Tümü</option>
              {activeBrands.map(b => <option key={b} value={b}>{b}</option>)}
          </select>
      </FilterSection>

      <FilterSection id="specs" title="Teknik Özellikler" icon={Cpu}>
          <div>
              <label className="text-[10px] font-bold text-slate-500 mb-1 block">İŞLEMCİ</label>
              <select value={filters.processor || ''} onChange={(e) => updateFilter('processor', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-2 focus:border-indigo-500 outline-none bg-white">
                  <option value="">Seçiniz</option>
                  {processors.map(p => <option key={p} value={p}>{p}</option>)}
              </select>
          </div>
          <div>
              <label className="text-[10px] font-bold text-slate-500 mb-1 block">RAM</label>
              <select value={filters.ram || ''} onChange={(e) => updateFilter('ram', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-2 focus:border-indigo-500 outline-none bg-white">
                  <option value="">Seçiniz</option>
                  {ramOptions.map(r => <option key={r} value={r}>{r}</option>)}
              </select>
          </div>
          <div>
              <label className="text-[10px] font-bold text-slate-500 mb-1 block">DEPOLAMA (SSD)</label>
              <select value={filters.ssd_capacity || ''} onChange={(e) => updateFilter('ssd_capacity', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-2 focus:border-indigo-500 outline-none bg-white">
                  <option value="">Seçiniz</option>
                  {ssdCapacities.map(s => <option key={s} value={s}>{s}</option>)}
              </select>
          </div>
          <div>
              <label className="text-[10px] font-bold text-slate-500 mb-1 block">EKRAN KARTI</label>
              <select value={filters.gpu_capacity || ''} onChange={(e) => updateFilter('gpu_capacity', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-2 focus:border-indigo-500 outline-none bg-white">
                  <option value="">Seçiniz</option>
                  {gpuCapacities.map(g => <option key={g} value={g}>{g}</option>)}
              </select>
          </div>
      </FilterSection>

      <FilterSection id="screen" title="Ekran" icon={Monitor}>
          <div>
              <label className="text-[10px] font-bold text-slate-500 mb-1 block">EKRAN BOYUTU</label>
              <select value={filters.screen_size || ''} onChange={(e) => updateFilter('screen_size', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-2 focus:border-indigo-500 outline-none bg-white">
                  <option value="">Seçiniz</option>
                  {screenSizes.map(s => <option key={s} value={s}>{s}</option>)}
              </select>
          </div>
      </FilterSection>

    </div>
  );
}
`;

// ---------------------------------------------------------
// 6. GÜNCELLENMİŞ İLAN VERME LAYOUT (STEPPER DÜZELTİLDİ)
// ---------------------------------------------------------
const layoutContent = `
"use client";
import React from 'react';
import { usePathname } from 'next/navigation';
import { Check, Layers, FileText } from 'lucide-react';

// DOPING VE ÖDEME ADIMLARI KALDIRILDI
const steps = [
  { id: 'category', label: 'Kategori', path: '/ilan-ver', icon: Layers },
  { id: 'details', label: 'İlan Detayı', path: '/ilan-ver/detay', icon: FileText },
];

export default function PostAdLayout({ children }) {
  const pathname = usePathname();

  // Aktif adımı bul
  const activeIndex = steps.findIndex(s => pathname === s.path || pathname.startsWith(s.path + '/'));
  const safeActiveIndex = activeIndex === -1 && pathname.includes('basarili') ? 2 : activeIndex;

  return (
    <div className="min-h-screen bg-gray-50/50 pb-20">
      {/* STEPPER HEADER */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-40 shadow-sm/50 backdrop-blur-md bg-white/90">
        <div className="container max-w-5xl mx-auto px-4">
          <div className="flex items-center justify-between py-4">

            {steps.map((step, idx) => {
              const isActive = idx === safeActiveIndex;
              const isCompleted = idx < safeActiveIndex;
              const Icon = step.icon;

              return (
                <div key={step.id} className="flex items-center flex-1 last:flex-none relative">
                  <div className={\`flex items-center gap-3 relative z-10 \${idx !== steps.length - 1 ? 'w-full' : ''}\`}>

                    {/* Circle */}
                    <div className={\`
                      w-10 h-10 rounded-full flex items-center justify-center text-sm font-bold transition-all duration-300 shadow-sm
                      \${isCompleted ? 'bg-green-500 text-white' : isActive ? 'bg-indigo-600 text-white ring-4 ring-indigo-50 scale-110' : 'bg-white border-2 border-gray-200 text-gray-400'}
                    \`}>
                      {isCompleted ? <Check size={18} /> : <Icon size={18} />}
                    </div>

                    {/* Label (Hidden on mobile) */}
                    <div className="hidden md:block">
                      <p className={\`text-xs font-bold uppercase tracking-wider mb-0.5 \${isActive ? 'text-indigo-600' : isCompleted ? 'text-green-600' : 'text-gray-400'}\`}>
                        Adım {idx + 1}
                      </p>
                      <p className={\`text-sm font-bold \${isActive || isCompleted ? 'text-gray-900' : 'text-gray-400'}\`}>
                        {step.label}
                      </p>
                    </div>

                    {/* Connecting Line */}
                    {idx !== steps.length - 1 && (
                      <div className="flex-1 h-[2px] mx-4 bg-gray-100 hidden sm:block overflow-hidden rounded-full">
                        <div className={\`h-full bg-green-500 transition-all duration-500 \${isCompleted ? 'w-full' : 'w-0'}\`}></div>
                      </div>
                    )}
                  </div>
                </div>
              );
            })}

          </div>
        </div>
      </div>

      {/* CONTENT */}
      <main className="container max-w-5xl mx-auto px-4 py-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
        {children}
      </main>
    </div>
  );
}
`;

// ---------------------------------------------------------
// 7. GÜNCELLENMİŞ İLAN DETAY FORMU (YÖNLENDİRME DÜZELTİLDİ)
// ---------------------------------------------------------
const postAdPageContent = `
"use client";
import React, { useState, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Loader2, ArrowLeft, Info, MapPin, Camera, Sparkles, Save, Cpu } from 'lucide-react';
import { useToast } from '@/context/ToastContext';
import { useAuth } from '@/context/AuthContext';
import ComputerFields from '@/components/form/ComputerFields';
import ImageUploader from '@/components/ui/ImageUploader';
import AdCard from '@/components/AdCard';
import { createAdAction } from '@/lib/actions';
import { adSchema } from '@/lib/schemas';
import { cities, getDistricts } from '@/lib/locations';
import { Input } from '@/components/ui/Input';
import { Textarea } from '@/components/ui/Textarea';

function PostAdFormContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { addToast } = useToast();
  const { user } = useAuth();

  const categorySlug = searchParams.get('cat') || '';
  const categoryPath = searchParams.get('path') || 'Kategori Seçilmedi';
  const urlBrand = searchParams.get('brand') || '';

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [images, setImages] = useState([]);
  const [errors, setErrors] = useState({});
  const [districts, setDistricts] = useState([]);
  const [lastSaved, setLastSaved] = useState(null);

  const [formData, setFormData] = useState({
    title: '', description: '', price: '', currency: 'TL', city: '', district: '',
    brand: urlBrand,
    processor: '', ram: '', screen_size: '', gpu_capacity: '', resolution: '', ssd_capacity: ''
  });

  useEffect(() => {
    if (urlBrand) setFormData(prev => ({ ...prev, brand: urlBrand }));
  }, [urlBrand]);

  useEffect(() => {
    if (formData.city) setDistricts(getDistricts(formData.city));
  }, [formData.city]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleDynamicChange = (name, value) => {
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!user) { router.push('/login'); return; }

    const rawData = {
        ...formData,
        category: categorySlug,
        image: images[0] || null,
        images: images,
        price: Number(formData.price),
    };

    const result = adSchema.safeParse(rawData);
    if (!result.success) {
        const fieldErrors = {};
        result.error.issues.forEach(issue => { fieldErrors[issue.path[0]] = issue.message; });
        setErrors(fieldErrors);
        addToast('Lütfen hatalı alanları düzeltiniz.', 'error');
        window.scrollTo({ top: 0, behavior: 'smooth' });
        return;
    }

    setIsSubmitting(true);
    const res = await createAdAction(rawData);
    if (res.error) { addToast(res.error, 'error'); }
    else {
        // BAŞARILI! Dopinge değil, direkt başarı sayfasına gönderiyoruz.
        addToast('İlan başarıyla oluşturuldu!', 'success');
        router.push('/ilan-ver/basarili');
    }
    setIsSubmitting(false);
  };

  return (
    <div className="flex flex-col lg:flex-row gap-8 relative">
      <div className="flex-1">
        <div className="bg-indigo-50 border border-indigo-100 p-4 rounded-xl mb-6 flex items-center justify-between">
          <div>
            <p className="text-xs font-bold text-indigo-600 uppercase tracking-wide mb-1">Kategori</p>
            <h1 className="text-sm md:text-base font-bold text-indigo-900">{categoryPath}</h1>
          </div>
          <button onClick={() => router.push('/ilan-ver')} className="text-xs font-bold text-slate-500 hover:text-indigo-600 bg-white px-3 py-1.5 rounded-lg border border-indigo-100 hover:border-indigo-300 transition-colors">Değiştir</button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-8">
          <section className="bg-white p-6 md:p-8 rounded-2xl shadow-sm border border-gray-100 relative overflow-hidden">
            <div className="absolute top-0 left-0 w-1 h-full bg-indigo-500"></div>
            <h3 className="text-lg font-bold text-slate-800 mb-6 flex items-center gap-2"><Info className="text-indigo-500" size={20}/> Temel Bilgiler</h3>
            <div className="space-y-5">
              <Input label="İlan Başlığı" name="title" placeholder="Örn: Macbook Pro M1, Çiziksiz..." value={formData.title} onChange={handleInputChange} error={errors.title} className="font-medium text-base" />
              <Textarea label="İlan Açıklaması" name="description" placeholder="Ürünün durumu, kutu içeriği vb." value={formData.description} onChange={handleInputChange} className="h-32" error={errors.description} />
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                <Input label="Fiyat" name="price" type="number" placeholder="0" value={formData.price} onChange={handleInputChange} error={errors.price} className="font-bold text-lg text-indigo-900" />
                <div>
                  <label className="block text-[11px] font-bold text-gray-600 mb-1">Para Birimi</label>
                  <div className="grid grid-cols-4 gap-2">
                    {['TL', 'USD', 'EUR', 'GBP'].map(curr => (
                      <button key={curr} type="button" onClick={() => setFormData({...formData, currency: curr})} className={\`h-10 rounded-lg text-sm font-bold border transition-all \${formData.currency === curr ? 'bg-indigo-600 text-white border-indigo-600 shadow-md' : 'bg-white text-gray-600 border-gray-200 hover:bg-gray-50'}\`}>{curr}</button>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Sadece Elektronik/Bilgisayar Alanlarını Gösteriyoruz */}
          <section className="bg-white p-6 md:p-8 rounded-2xl shadow-sm border border-gray-100 relative overflow-hidden">
            <div className="absolute top-0 left-0 w-1 h-full bg-orange-500"></div>
            <h3 className="text-lg font-bold text-slate-800 mb-6 flex items-center gap-2"><Cpu className="text-orange-500" size={20}/> Teknik Detaylar</h3>
            <div className="-mx-4 md:mx-0">
                <ComputerFields data={formData} onChange={handleDynamicChange} categorySlug={categorySlug} />
            </div>
          </section>

          <section className="bg-white p-6 md:p-8 rounded-2xl shadow-sm border border-gray-100 relative overflow-hidden">
            <div className="absolute top-0 left-0 w-1 h-full bg-pink-500"></div>
            <h3 className="text-lg font-bold text-slate-800 mb-2 flex items-center gap-2"><Camera className="text-pink-500" size={20}/> Fotoğraflar</h3>
            <p className="text-sm text-slate-500 mb-6">İlk yüklediğiniz fotoğraf vitrin görseli olacaktır.</p>
            <div className="bg-slate-50 p-4 rounded-xl border border-dashed border-slate-300"><ImageUploader onImagesChange={setImages} initialImages={images} /></div>
          </section>

          <section className="bg-white p-6 md:p-8 rounded-2xl shadow-sm border border-gray-100 relative overflow-hidden">
            <div className="absolute top-0 left-0 w-1 h-full bg-green-500"></div>
            <h3 className="text-lg font-bold text-slate-800 mb-6 flex items-center gap-2"><MapPin className="text-green-500" size={20}/> Konum Bilgisi</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              <div>
                <label className="block text-[11px] font-bold text-gray-600 mb-1">İl <span className="text-red-500">*</span></label>
                <select name="city" onChange={handleInputChange} value={formData.city} className="w-full h-11 pl-3 pr-8 bg-white border border-gray-300 rounded-lg outline-none focus:border-green-500 focus:ring-1 focus:ring-green-500 appearance-none text-sm transition-shadow shadow-sm">
                    <option value="">Seçiniz</option>{cities.map(c => <option key={c} value={c}>{c}</option>)}
                </select>
              </div>
              <div>
                <label className="block text-[11px] font-bold text-gray-600 mb-1">İlçe <span className="text-red-500">*</span></label>
                <select name="district" value={formData.district} onChange={handleInputChange} className="w-full h-11 pl-3 pr-8 bg-white border border-gray-300 rounded-lg outline-none focus:border-green-500 focus:ring-1 focus:ring-green-500 appearance-none text-sm transition-shadow shadow-sm disabled:bg-gray-100" disabled={!formData.city}>
                    <option value="">Seçiniz</option>{districts.map(d => <option key={d} value={d}>{d}</option>)}
                </select>
              </div>
            </div>
          </section>

          <div className="flex items-center justify-between pt-4 pb-20 lg:pb-0">
            <button type="button" onClick={() => router.back()} className="px-6 py-3 rounded-lg font-bold text-sm text-slate-600 hover:bg-slate-100 flex items-center gap-2 transition-colors"><ArrowLeft size={18}/> Geri Dön</button>
            <button type="submit" disabled={isSubmitting} className="bg-indigo-600 text-white px-10 py-4 rounded-xl font-bold text-base hover:bg-indigo-700 transition-all disabled:opacity-50 flex items-center gap-2">{isSubmitting ? <Loader2 className="animate-spin" size={20}/> : 'İlanı Yayınla'}</button>
          </div>
        </form>
      </div>
    </div>
  );
}

export default function PostAdPage() {
    return <Suspense fallback={<div className="p-20 text-center"><Loader2 className="animate-spin mx-auto text-indigo-600" size={32}/></div>}><PostAdFormContent /></Suspense>
}
`;

// ---------------------------------------------------------
// 8. İLAN ÖZELLİK TABLOSU (components/AdDetail/FeaturesTab.tsx)
// ---------------------------------------------------------
const featuresTabContent = `
import React from 'react';

export default function FeaturesTab({ ad }) {
  const renderRow = (label, value) => {
    if (value === null || value === undefined || value === '') return null;
    let displayValue = value;
    if (typeof value === 'boolean') displayValue = value ? 'Evet' : 'Hayır';

    return (
       <div className="flex justify-between border-b border-gray-100 py-3 text-sm hover:bg-gray-50 px-2 transition-colors last:border-0">
          <span className="font-semibold text-gray-600 w-1/2">{label}</span>
          <span className="text-gray-900 font-bold w-1/2 text-right">{displayValue}</span>
       </div>
    );
  };

  return (
    <div className="bg-white border border-gray-200 rounded-lg p-4 shadow-sm">
       <h4 className="font-bold text-gray-800 text-sm uppercase tracking-wider mb-4 border-b pb-2">Teknik Özellikler</h4>
       <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-1">
          {renderRow('Marka', ad.brand)}
          {renderRow('Model', ad.model)}
          {renderRow('İşlemci', ad.processor)}
          {renderRow('RAM', ad.ram)}
          {renderRow('Ekran Boyutu', ad.screen_size)}
          {renderRow('Ekran Kartı', ad.gpu_capacity)}
          {renderRow('Depolama (SSD)', ad.ssd_capacity)}
          {renderRow('Çözünürlük', ad.resolution)}
          {renderRow('Kategori', ad.category)}
       </div>
    </div>
  );
}
`;

// ---------------------------------------------------------
// 9. CATEGORY WIZARD (components/CategoryWizard.tsx)
// ---------------------------------------------------------
const categoryWizardContentNew = `
"use client";
import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ChevronRight, ArrowLeft, Monitor, Smartphone, Camera, Tv, Gamepad2, Plug, CheckCircle2, Laptop } from 'lucide-react';
import { categoryTree, computerBrands, phoneBrands } from '@/lib/hierarchyData';

const iconMap = {
  Monitor: <Monitor size={28} />,
  Smartphone: <Smartphone size={28} />,
  Camera: <Camera size={28} />,
  Tv: <Tv size={28} />,
  Gamepad2: <Gamepad2 size={28} />,
  Plug: <Plug size={28} />,
  Laptop: <Laptop size={28} />
};

export default function CategoryWizard() {
  const router = useRouter();
  const [history, setHistory] = useState([]);
  const [currentList, setCurrentList] = useState(categoryTree);
  const [selectedPath, setSelectedPath] = useState([]);
  const [isBrandSelection, setIsBrandSelection] = useState(false);

  const handleSelect = (item) => {
    // 1. Dinamik Marka Seçimi (Bilgisayar veya Telefon)
    if (item.isDynamic) {
        setIsBrandSelection(true);
        setHistory([...history, currentList]);
        setSelectedPath([...selectedPath, item.title]);

        let brands = [];
        if (item.dynamicType === 'computer') brands = computerBrands;
        if (item.dynamicType === 'phone') brands = phoneBrands;

        const brandList = brands.map(brand => ({
            id: brand,
            title: brand,
            slug: brand.toLowerCase().replace(/ /g, '-'),
            isFinal: true
        }));
        setCurrentList(brandList);
        return;
    }

    // 2. Marka Seçildiyse -> Bitiş
    if (isBrandSelection) {
        const brand = item.title;
        const finalPath = [...selectedPath, brand].join(' > ');
        router.push(\`/ilan-ver/detay?cat=\${selectedPath[0]?.toLowerCase().includes('bilgisayar') ? 'laptop' : 'cep-telefonu'}&path=\${encodeURIComponent(finalPath)}&brand=\${encodeURIComponent(brand)}\`);
        return;
    }

    // 3. Normal Kategori Gezinimi
    const newPath = [...selectedPath, item.title];

    if (item.subs && item.subs.length > 0) {
      setHistory([...history, currentList]);
      setCurrentList(item.subs);
      setSelectedPath(newPath);
    } else {
      router.push(\`/ilan-ver/detay?cat=\${item.slug}&path=\${newPath.join(' > ')}\`);
    }
  };

  const handleBack = () => {
    if (history.length === 0) return;
    const prevList = history[history.length - 1];
    setHistory(history.slice(0, -1));
    setCurrentList(prevList);
    setSelectedPath(selectedPath.slice(0, -1));
    if (isBrandSelection) setIsBrandSelection(false);
  };

  return (
    <div className="w-full">
      <div className="flex items-center gap-4 mb-6">
        {history.length > 0 && (
          <button onClick={handleBack} className="w-10 h-10 rounded-full bg-white border border-gray-200 flex items-center justify-center text-gray-600 hover:bg-indigo-50 hover:text-indigo-600 transition-all shadow-sm">
            <ArrowLeft size={20} />
          </button>
        )}
        <div>
          <h2 className="text-xl font-bold text-slate-900">
            {history.length === 0 ? 'Elektronik Kategori Seçimi' : selectedPath[selectedPath.length - 1] || 'Seçim Yapınız'}
          </h2>
          <p className="text-sm text-slate-500">
            {history.length === 0 ? 'Satmak istediğiniz ürünün kategorisini seçin.' : selectedPath.join(' > ')}
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {currentList.map((item) => {
          const Icon = iconMap[item.icon] || null;
          const isLeaf = (!item.subs || item.subs.length === 0) || item.isFinal;

          return (
            <button
              key={item.id || item.title}
              onClick={() => handleSelect(item)}
              className="group relative flex items-center p-5 bg-white border border-gray-200 rounded-xl hover:border-indigo-500 hover:shadow-md transition-all duration-200 text-left"
            >
              <div className={\`w-14 h-14 rounded-lg flex items-center justify-center mr-4 transition-colors shrink-0 \${history.length === 0 ? 'bg-indigo-50 text-indigo-600 group-hover:bg-indigo-600 group-hover:text-white' : 'bg-gray-100 text-gray-500 group-hover:bg-indigo-100 group-hover:text-indigo-700'}\`}>
                {history.length === 0 && Icon ? Icon : (isLeaf ? <CheckCircle2 size={24} className="text-green-600" /> : <div className="text-sm font-bold opacity-50">{item.title.substring(0,2).toUpperCase()}</div>)}
              </div>
              <div className="flex-1 min-w-0">
                <span className="block font-bold text-slate-700 group-hover:text-indigo-900 text-base mb-0.5 truncate">{item.title}</span>
                <span className="text-xs text-slate-400 group-hover:text-indigo-500 font-medium">
                    {isLeaf ? 'Seç ve Devam Et' : 'Alt Kategorileri Gör'}
                </span>
              </div>
              <div className="absolute right-4 opacity-0 group-hover:opacity-100 transition-opacity transform group-hover:translate-x-1">
                {isLeaf ? <CheckCircle2 size={20} className="text-green-500" /> : <ChevronRight size={20} className="text-indigo-400" />}
              </div>
            </button>
          );
        })}
      </div>
    </div>
  );
}
`;

// ---------------------------------------------------------
// 10. ÖDEME VE DOPING SAYFALARINI KAPATMA
// ---------------------------------------------------------
const redirectPageContent = `
import { redirect } from 'next/navigation';

export default function RedirectPage() {
  redirect('/');
}
`;

// Dosyaları yazma işlemi
const filesToWrite = [
  { path: "supabase/seed_electronics.sql", content: sqlContent },
  { path: "lib/data.ts", content: dataTsContent },
  { path: "lib/hierarchyData.ts", content: hierarchyDataContent },
  { path: "lib/schemas.ts", content: schemaContent },
  { path: "components/FilterSidebar.tsx", content: filterSidebarContent },
  { path: "app/ilan-ver/layout.tsx", content: layoutContent },
  { path: "app/ilan-ver/detay/page.tsx", content: postAdPageContent },
  { path: "components/AdDetail/FeaturesTab.tsx", content: featuresTabContent },
  { path: "components/CategoryWizard.tsx", content: categoryWizardContentNew },
  { path: "app/ilan-ver/odeme/page.tsx", content: redirectPageContent },
  { path: "app/ilan-ver/doping/page.tsx", content: redirectPageContent },
];

filesToWrite.forEach((file) => {
  try {
    const dir = path.dirname(file.path);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    fs.writeFileSync(path.join(process.cwd(), file.path), file.content.trim());
    console.log(
      colors.green + "✔ " + file.path + " güncellendi." + colors.reset,
    );
  } catch (e) {
    console.error(
      colors.yellow +
        "✘ " +
        file.path +
        " yazılamadı: " +
        e.message +
        colors.reset,
    );
  }
});

console.log(
  colors.blue +
    colors.bold +
    "\n✅ SISTEM DOPINGSIZ VE ODEMESIZ HALE GETIRILDI!" +
    colors.reset,
);
console.log(
  "Lütfen 'supabase/seed_electronics.sql' dosyasındaki kodu Supabase SQL Editor'de çalıştırın.",
);
