const fs = require("fs");
const path = require("path");

const colors = {
  reset: "\x1b[0m",
  green: "\x1b[32m",
  blue: "\x1b[34m",
  yellow: "\x1b[33m",
  bold: "\x1b[1m",
};

console.log(
  colors.blue +
    colors.bold +
    "\n🇺🇸  TRANSFORMING TO ELECTRONIC-USA (ENGLISH ONLY)...\n" +
    colors.reset,
);

// ---------------------------------------------------------
// 1. SQL MIGRATION (English Categories)
// ---------------------------------------------------------
const sqlContent = `
-- RUN THIS IN SUPABASE SQL EDITOR --

-- 1. Reset Categories
TRUNCATE TABLE categories CASCADE;
ALTER TABLE categories ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 2. Main Categories
INSERT INTO categories (id, title, slug, icon, parent_id) VALUES
(1, 'Computing', 'computing', 'Monitor', NULL),
(2, 'Phones & Accessories', 'phones', 'Smartphone', NULL),
(3, 'Gaming & Consoles', 'gaming', 'Gamepad2', NULL),
(4, 'TV & Audio', 'audio-video', 'Tv', NULL),
(5, 'Cameras & Drones', 'cameras', 'Camera', NULL),
(6, 'Smart Home', 'smart-home', 'Zap', NULL);

-- 3. Update Sequence
SELECT setval(pg_get_serial_sequence('categories', 'id'), (SELECT MAX(id) FROM categories));

-- 4. Sub Categories
INSERT INTO categories (title, slug, icon, parent_id) VALUES
('Laptops', 'laptops', 'Laptop', 1),
('Desktops', 'desktops', 'Monitor', 1),
('Tablets', 'tablets', 'Tablet', 1),
('Components', 'components', 'Cpu', 1),
('Networking', 'networking', 'Wifi', 1),

('Smartphones', 'smartphones', 'Smartphone', 2),
('Smart Watches', 'wearables', 'Watch', 2),
('Cases & Protection', 'cases', 'Shield', 2),

('Consoles', 'consoles', 'Gamepad', 3),
('Video Games', 'games', 'Disc', 3),
('Accessories', 'gaming-accessories', 'Keyboard', 3),

('Televisions', 'tvs', 'Tv', 4),
('Headphones', 'headphones', 'Headphones', 4),
('Speakers', 'speakers', 'Speaker', 4),

('Digital Cameras', 'digital-cameras', 'Camera', 5),
('Drones', 'drones', 'Plane', 5),

('Robot Vacuums', 'robot-vacuums', 'Bot', 6),
('Smart Lighting', 'smart-lighting', 'Zap', 6);
`;

// ---------------------------------------------------------
// 2. LOCATION DATA (lib/locations.ts)
// ---------------------------------------------------------
const locationsContent = `
export const cities = [
  { name: 'New York', districts: ['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island'] },
  { name: 'California', districts: ['Los Angeles', 'San Francisco', 'San Diego', 'San Jose', 'Sacramento'] },
  { name: 'Texas', districts: ['Houston', 'Austin', 'Dallas', 'San Antonio', 'Fort Worth'] },
  { name: 'Florida', districts: ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Tallahassee'] },
  { name: 'Illinois', districts: ['Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio'] },
  { name: 'Washington', districts: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'] },
  { name: 'Nevada', districts: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks'] },
  { name: 'Massachusetts', districts: ['Chicago', 'Aurora', 'Naperville', 'Joliet', 'Rockford'] }
];

export const getDistricts = (cityName: string) => {
  const city = cities.find(c => c.name === cityName);
  return city ? city.districts.sort() : [];
};
`;

// ---------------------------------------------------------
// 3. FRONTEND DATA (lib/data.ts)
// ---------------------------------------------------------
const dataTsContent = `
import { Monitor, Smartphone, Camera, Tv, Gamepad2, Plug, Cpu, Laptop, Watch, Headphones, Speaker, Shield, Zap, Wifi, Disc, Keyboard, Mouse, Bot, Plane } from 'lucide-react';

export const categories = [
  {
    id: 'computing', title: 'Computing', icon: 'Monitor', slug: 'computing',
    subs: [
      { id: 'laptops', title: 'Laptops', slug: 'laptops', icon: 'Laptop' },
      { id: 'desktops', title: 'Desktops', slug: 'desktops', icon: 'Monitor' },
      { id: 'tablets', title: 'Tablets', slug: 'tablets', icon: 'Tablet' },
      { id: 'components', title: 'Components', slug: 'components', icon: 'Cpu' },
      { id: 'networking', title: 'Networking', slug: 'networking', icon: 'Wifi' }
    ]
  },
  {
    id: 'phones', title: 'Phones & Accessories', icon: 'Smartphone', slug: 'phones',
    subs: [
      { id: 'smartphones', title: 'Smartphones', slug: 'smartphones', icon: 'Smartphone' },
      { id: 'wearables', title: 'Smart Watches', slug: 'wearables', icon: 'Watch' },
      { id: 'cases', title: 'Cases & Protection', slug: 'cases', icon: 'Shield' }
    ]
  },
  {
    id: 'gaming', title: 'Gaming', icon: 'Gamepad2', slug: 'gaming',
    subs: [
      { id: 'consoles', title: 'Consoles', slug: 'consoles', icon: 'Gamepad2' },
      { id: 'games', title: 'Video Games', slug: 'games', icon: 'Disc' },
      { id: 'accessories', title: 'Accessories', slug: 'gaming-accessories', icon: 'Keyboard' }
    ]
  },
  {
    id: 'audio', title: 'TV & Audio', icon: 'Tv', slug: 'audio-video',
    subs: [
      { id: 'tvs', title: 'Televisions', slug: 'tvs', icon: 'Tv' },
      { id: 'headphones', title: 'Headphones', slug: 'headphones', icon: 'Headphones' },
      { id: 'speakers', title: 'Speakers', slug: 'speakers', icon: 'Speaker' }
    ]
  },
  {
    id: 'cameras', title: 'Cameras', icon: 'Camera', slug: 'cameras',
    subs: [
      { id: 'digital', title: 'Digital Cameras', slug: 'digital-cameras', icon: 'Camera' },
      { id: 'drones', title: 'Drones', slug: 'drones', icon: 'Plane' }
    ]
  }
];
`;

// ---------------------------------------------------------
// 4. HIERARCHY DATA (lib/hierarchyData.ts)
// ---------------------------------------------------------
const hierarchyDataContent = `
import { Monitor, Smartphone, Camera, Tv, Gamepad2 } from 'lucide-react';

export type CategoryNode = {
  id: string;
  title: string;
  slug: string;
  icon?: any;
  subs?: CategoryNode[];
  isDynamic?: boolean;
  dynamicType?: 'computer' | 'phone';
};

export const categoryTree: CategoryNode[] = [
  {
    id: 'computing', title: 'Computing', icon: 'Monitor', slug: 'computing',
    subs: [
      { id: 'laptops', title: 'Laptops', slug: 'laptops', isDynamic: true, dynamicType: 'computer' },
      { id: 'desktops', title: 'Desktops', slug: 'desktops' },
      { id: 'tablets', title: 'Tablets', slug: 'tablets' },
      { id: 'components', title: 'PC Components', slug: 'components' }
    ]
  },
  {
    id: 'phones', title: 'Phones', icon: 'Smartphone', slug: 'phones',
    subs: [
      { id: 'smartphones', title: 'Smartphones', slug: 'smartphones', isDynamic: true, dynamicType: 'phone' },
      { id: 'accessories', title: 'Accessories', slug: 'cases' }
    ]
  },
  {
    id: 'gaming', title: 'Gaming', icon: 'Gamepad2', slug: 'gaming',
    subs: [
      { id: 'consoles', title: 'Consoles', slug: 'consoles' }
    ]
  }
];

export const carHierarchy: Record<string, Record<string, string[]>> = {};

export const computerBrands = [
  "Apple", "Dell", "HP", "Lenovo", "Asus", "Acer", "MSI", "Razer", "Microsoft", "Samsung", "Toshiba"
];

export const phoneBrands = [
  "Apple", "Samsung", "Google", "OnePlus", "Motorola", "Xiaomi", "Sony", "Nokia"
];
`;

// ---------------------------------------------------------
// 5. SCHEMAS (lib/schemas.ts)
// ---------------------------------------------------------
const schemaContent = `
import { z } from 'zod';

export const adSchema = z.object({
  title: z.string().min(5, "Title must be at least 5 characters").max(100, "Title is too long"),
  description: z.string().min(10, "Description must be at least 10 characters"),
  price: z.number({ invalid_type_error: "Please enter a valid price" }).min(0, "Price cannot be negative"),
  currency: z.enum(['USD', 'EUR', 'GBP']), // Removed TL
  city: z.string().min(1, "City selection is required"),
  district: z.string().min(1, "District selection is required"),
  category: z.string().min(1, "Category is required"),
  image: z.string().nullable().optional(),
  images: z.array(z.string()).optional(),

  // Electronic Specifics
  brand: z.string().optional().nullable(),
  model: z.string().optional().nullable(),
  processor: z.string().optional().nullable(),
  ram: z.string().optional().nullable(),
  screen_size: z.string().optional().nullable(),
  gpu_capacity: z.string().optional().nullable(),
  resolution: z.string().optional().nullable(),
  ssd_capacity: z.string().optional().nullable(),

  // Legacy fields (kept optional to avoid breaks)
  year: z.any().optional().nullable(),
  km: z.any().optional().nullable(),
  m2: z.any().optional().nullable(),
  room: z.any().optional().nullable(),
  technical_specs: z.any().optional().nullable()
});

export type AdFormValues = z.infer<typeof adSchema>;
`;

// ---------------------------------------------------------
// 6. FILTER SIDEBAR (components/FilterSidebar.tsx)
// ---------------------------------------------------------
const filterSidebarContent = `
"use client";
import React, { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Filter, RotateCcw, ChevronDown, ChevronUp, Search, Cpu, Monitor } from 'lucide-react';
import { computerBrands, phoneBrands } from '@/lib/hierarchyData';
import { processors, ramOptions, screenSizes, gpuCapacities, ssdCapacities } from '@/lib/computerData';

export default function FilterSidebar() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [filters, setFilters] = useState({});
  const [expanded, setExpanded] = useState({
      brand: true, specs: true, price: true
  });

  useEffect(() => {
    const newFilters = {};
    searchParams.forEach((value, key) => { newFilters[key] = value; });
    setFilters(newFilters);
  }, [searchParams]);

  const updateFilter = (key, value) => {
      setFilters((prev) => {
          const next = { ...prev, [key]: value };
          if (!value) delete next[key];
          return next;
      });
  };

  const applyFilters = () => {
    const params = new URLSearchParams();
    Object.entries(filters).forEach(([key, value]) => {
        if (value) params.set(key, value);
    });
    params.set('showResults', 'true');
    router.push(\`/search?\${params.toString()}\`);
  };

  const clearFilters = () => {
    router.push('/search');
  };

  const toggle = (id) => setExpanded(prev => ({ ...prev, [id]: !prev[id] }));

  // Brands logic
  const cat = filters.category || '';
  let activeBrands = computerBrands;
  if (cat.includes('phone') || cat.includes('mobile')) activeBrands = phoneBrands;

  const FilterSection = ({ id, title, icon: Icon, children }) => (
      <div className="border-b border-gray-100 py-4 last:border-0">
          <button onClick={() => toggle(id)} className="flex items-center justify-between w-full text-left mb-2 group">
              <span className="text-xs font-bold text-slate-700 uppercase tracking-wide flex items-center gap-2 group-hover:text-blue-600 transition-colors">
                  {Icon && <Icon size={14} className="text-slate-400 group-hover:text-blue-500"/>} {title}
              </span>
              {expanded[id] ? <ChevronUp size={14} className="text-gray-400"/> : <ChevronDown size={14} className="text-gray-400"/>}
          </button>
          {expanded[id] && <div className="space-y-3 pt-2 animate-in slide-in-from-top-1">{children}</div>}
      </div>
  );

  return (
    <div className="bg-white border border-gray-200 rounded-xl shadow-sm p-5 sticky top-24">

      <div className="mb-6 bg-indigo-50/50 p-4 rounded-xl border border-indigo-100">
        <h3 className="font-bold text-indigo-900 text-sm mb-3 flex items-center gap-2">
            <Filter size={16} /> Filters
        </h3>
        <button onClick={applyFilters} className="w-full bg-indigo-600 text-white text-sm font-bold py-2.5 rounded-lg hover:bg-indigo-700 transition-all shadow-sm flex items-center justify-center gap-2">
            <Search size={16} /> Show Results
        </button>
        <button onClick={clearFilters} className="w-full text-center text-xs text-slate-500 hover:text-red-600 mt-2 flex items-center justify-center gap-1 font-medium transition-colors">
            <RotateCcw size={12}/> Clear All
        </button>
      </div>

      <FilterSection id="price" title="Price Range">
          <div className="flex gap-2 items-center">
              <input type="number" placeholder="Min $" value={filters.minPrice || ''} onChange={(e) => updateFilter('minPrice', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-3 outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500" />
              <span className="text-gray-400">-</span>
              <input type="number" placeholder="Max $" value={filters.maxPrice || ''} onChange={(e) => updateFilter('maxPrice', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-3 outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500" />
          </div>
      </FilterSection>

      <FilterSection id="brand" title="Brand">
          <select value={filters.brand || ''} onChange={(e) => updateFilter('brand', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-2 focus:border-indigo-500 outline-none bg-white">
              <option value="">All Brands</option>
              {activeBrands.map(b => <option key={b} value={b}>{b}</option>)}
          </select>
      </FilterSection>

      <FilterSection id="specs" title="Technical Specs" icon={Cpu}>
          <div>
              <label className="text-[10px] font-bold text-slate-500 mb-1 block">PROCESSOR</label>
              <select value={filters.processor || ''} onChange={(e) => updateFilter('processor', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-2 focus:border-indigo-500 outline-none bg-white">
                  <option value="">Select</option>
                  {processors.map(p => <option key={p} value={p}>{p}</option>)}
              </select>
          </div>
          <div>
              <label className="text-[10px] font-bold text-slate-500 mb-1 block">RAM</label>
              <select value={filters.ram || ''} onChange={(e) => updateFilter('ram', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-2 focus:border-indigo-500 outline-none bg-white">
                  <option value="">Select</option>
                  {ramOptions.map(r => <option key={r} value={r}>{r}</option>)}
              </select>
          </div>
          <div>
              <label className="text-[10px] font-bold text-slate-500 mb-1 block">STORAGE (SSD)</label>
              <select value={filters.ssd_capacity || ''} onChange={(e) => updateFilter('ssd_capacity', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-2 focus:border-indigo-500 outline-none bg-white">
                  <option value="">Select</option>
                  {ssdCapacities.map(s => <option key={s} value={s}>{s}</option>)}
              </select>
          </div>
      </FilterSection>

      <FilterSection id="screen" title="Screen" icon={Monitor}>
          <div>
              <label className="text-[10px] font-bold text-slate-500 mb-1 block">SCREEN SIZE</label>
              <select value={filters.screen_size || ''} onChange={(e) => updateFilter('screen_size', e.target.value)} className="w-full border border-gray-300 rounded-lg text-xs h-9 px-2 focus:border-indigo-500 outline-none bg-white">
                  <option value="">Select</option>
                  {screenSizes.map(s => <option key={s} value={s}>{s}</option>)}
              </select>
          </div>
      </FilterSection>

    </div>
  );
}
`;

// ---------------------------------------------------------
// 7. POST AD PAGE (English & Fixed)
// ---------------------------------------------------------
const postAdPageContent = `
"use client";
import React, { useState, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Loader2, ArrowLeft, Info, MapPin, Camera, Sparkles, Save, Cpu } from 'lucide-react';
import { useToast } from '@/context/ToastContext';
import { useAuth } from '@/context/AuthContext';
import ComputerFields from '@/components/form/ComputerFields';
import ImageUploader from '@/components/ui/ImageUploader';
import AdCard from '@/components/AdCard';
import { createAdAction } from '@/lib/actions';
import { adSchema } from '@/lib/schemas';
import { cities, getDistricts } from '@/lib/locations';
import { Input } from '@/components/ui/Input';
import { Textarea } from '@/components/ui/Textarea';

function PostAdFormContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { addToast } = useToast();
  const { user } = useAuth();

  const categorySlug = searchParams.get('cat') || '';
  const categoryPath = searchParams.get('path') || 'No Category Selected';
  const urlBrand = searchParams.get('brand') || '';

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [images, setImages] = useState([]);
  const [errors, setErrors] = useState({});
  const [districts, setDistricts] = useState([]);

  const [formData, setFormData] = useState({
    title: '', description: '', price: '', currency: 'USD', city: '', district: '',
    brand: urlBrand,
    processor: '', ram: '', screen_size: '', gpu_capacity: '', resolution: '', ssd_capacity: ''
  });

  useEffect(() => {
    if (urlBrand) setFormData(prev => ({ ...prev, brand: urlBrand }));
  }, [urlBrand]);

  useEffect(() => {
    if (formData.city) setDistricts(getDistricts(formData.city));
  }, [formData.city]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleDynamicChange = (e) => {
     const { name, value } = e.target;
     setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!user) { router.push('/login'); return; }

    const rawData = {
        ...formData,
        category: categorySlug,
        image: images[0] || null,
        images: images,
        price: Number(formData.price),
    };

    const result = adSchema.safeParse(rawData);
    if (!result.success) {
        const fieldErrors = {};
        result.error.issues.forEach(issue => { fieldErrors[issue.path[0]] = issue.message; });
        setErrors(fieldErrors);
        addToast('Please fill in required fields.', 'error');
        window.scrollTo({ top: 0, behavior: 'smooth' });
        return;
    }

    setIsSubmitting(true);
    const res = await createAdAction(rawData);
    if (res.error) { addToast(res.error, 'error'); }
    else {
        addToast('Ad published successfully!', 'success');
        router.push('/ilan-ver/basarili');
    }
    setIsSubmitting(false);
  };

  return (
    <div className="flex flex-col lg:flex-row gap-8 relative">
      <div className="flex-1">
        <div className="bg-indigo-50 border border-indigo-100 p-4 rounded-xl mb-6 flex items-center justify-between">
          <div>
            <p className="text-xs font-bold text-indigo-600 uppercase tracking-wide mb-1">Category</p>
            <h1 className="text-sm md:text-base font-bold text-indigo-900">{categoryPath}</h1>
          </div>
          <button onClick={() => router.push('/ilan-ver')} className="text-xs font-bold text-slate-500 hover:text-indigo-600 bg-white px-3 py-1.5 rounded-lg border border-indigo-100 hover:border-indigo-300 transition-colors">Change</button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-8">
          <section className="bg-white p-6 md:p-8 rounded-2xl shadow-sm border border-gray-100 relative overflow-hidden">
             <div className="absolute top-0 left-0 w-1 h-full bg-indigo-500"></div>
             <h3 className="text-lg font-bold text-slate-800 mb-6 flex items-center gap-2"><Info className="text-indigo-500" size={20}/> Basic Information</h3>
             <div className="space-y-5">
               <Input label="Ad Title" name="title" placeholder="Ex: Macbook Pro M1, Like New..." value={formData.title} onChange={handleInputChange} error={errors.title} />
               <Textarea label="Description" name="description" placeholder="Describe your product..." value={formData.description} onChange={handleInputChange} className="h-32" error={errors.description} />
               <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                 <Input label="Price" name="price" type="number" placeholder="0" value={formData.price} onChange={handleInputChange} error={errors.price} />
                 <div>
                   <label className="block text-[11px] font-bold text-gray-600 mb-1">Currency</label>
                   <select name="currency" value={formData.currency} onChange={handleInputChange} className="w-full h-10 border border-gray-300 rounded-sm px-2 text-sm bg-white outline-none">
                     <option value="USD">USD</option><option value="EUR">EUR</option><option value="GBP">GBP</option>
                   </select>
                 </div>
               </div>
             </div>
          </section>

          <section className="bg-white p-6 md:p-8 rounded-2xl shadow-sm border border-gray-100 relative overflow-hidden">
             <div className="absolute top-0 left-0 w-1 h-full bg-orange-500"></div>
             <h3 className="text-lg font-bold text-slate-800 mb-6 flex items-center gap-2"><Cpu className="text-orange-500" size={20}/> Tech Specs</h3>
             <ComputerFields data={formData} onChange={handleDynamicChange} categorySlug={categorySlug} />
          </section>

          <section className="bg-white p-6 md:p-8 rounded-2xl shadow-sm border border-gray-100 relative overflow-hidden">
             <div className="absolute top-0 left-0 w-1 h-full bg-green-500"></div>
             <h3 className="text-lg font-bold text-slate-800 mb-6 flex items-center gap-2"><MapPin className="text-green-500" size={20}/> Location</h3>
             <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
               <div>
                 <label className="block text-[11px] font-bold text-gray-600 mb-1">State / City</label>
                 <select name="city" onChange={handleInputChange} value={formData.city} className="w-full h-11 px-3 bg-white border border-gray-300 rounded-lg outline-none text-sm">
                    <option value="">Select</option>
                    {cities.map(c => <option key={c.name} value={c.name}>{c.name}</option>)}
                 </select>
               </div>
               <div>
                 <label className="block text-[11px] font-bold text-gray-600 mb-1">District / Area</label>
                 <select name="district" value={formData.district} onChange={handleInputChange} className="w-full h-11 px-3 bg-white border border-gray-300 rounded-lg outline-none text-sm" disabled={!formData.city}>
                    <option value="">Select</option>
                    {districts.map(d => <option key={d} value={d}>{d}</option>)}
                 </select>
               </div>
             </div>
          </section>

          <section className="bg-white p-6 md:p-8 rounded-2xl shadow-sm border border-gray-100 relative overflow-hidden">
             <div className="absolute top-0 left-0 w-1 h-full bg-pink-500"></div>
             <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2"><Camera className="text-pink-500" size={20}/> Photos</h3>
             <ImageUploader onImagesChange={setImages} initialImages={images} />
          </section>

          <div className="flex justify-end pt-4">
             <button type="submit" disabled={isSubmitting} className="bg-indigo-600 text-white px-10 py-4 rounded-xl font-bold hover:bg-indigo-700 transition-all flex items-center gap-2 disabled:opacity-50">
                {isSubmitting ? <Loader2 className="animate-spin" size={20}/> : 'Publish Ad'}
             </button>
          </div>
        </form>
      </div>
    </div>
  );
}

export default function PostAdPage() {
    return <Suspense fallback={<div className="p-20 text-center"><Loader2 className="animate-spin mx-auto text-indigo-600" size={32}/></div>}><PostAdFormContent /></Suspense>
}
`;

// ---------------------------------------------------------
// 8. HEADER (components/Header.tsx)
// ---------------------------------------------------------
const headerContent = `
"use client";
import React, { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Search, Plus, User, LogOut, LayoutDashboard, List, Loader2 } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';

export default function Header() {
  const [searchTerm, setSearchTerm] = useState('');
  const router = useRouter();
  const { user, logout } = useAuth();
  const [menuOpen, setMenuOpen] = useState(false);

  const handleSearch = (e) => {
    e.preventDefault();
    if (searchTerm.trim()) router.push(\`/search?q=\${encodeURIComponent(searchTerm)}\`);
  };

  return (
    <header className="bg-white/95 backdrop-blur-md border-b border-gray-200 h-[80px] flex items-center justify-center sticky top-0 z-50">
      <div className="container max-w-7xl flex items-center justify-between px-6 h-full">

        <div className="flex items-center">
          <Link href="/" className="flex items-center gap-2 group">
            <div className="w-10 h-10 bg-indigo-600 text-white rounded-xl flex items-center justify-center font-bold text-xl shadow-lg">E</div>
            <span className="font-bold text-2xl tracking-tight text-slate-800 hidden sm:block">Electronic<span className="text-indigo-600">USA</span></span>
          </Link>
        </div>

        <div className="flex-1 max-w-[500px] mx-8 hidden md:block">
          <form onSubmit={handleSearch} className="relative">
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search products..."
              className="w-full h-[50px] pl-12 pr-4 bg-gray-50 border border-gray-200 rounded-full focus:outline-none focus:ring-2 focus:ring-indigo-100 focus:border-indigo-500 transition-all text-sm"
            />
            <Search size={20} className="absolute left-4 top-[15px] text-gray-400" />
          </form>
        </div>

        <div className="flex items-center gap-4">
            <Link href="/ilan-ver" className="bg-indigo-600 text-white px-6 py-3 rounded-full text-sm font-bold hover:bg-indigo-700 transition-all flex items-center gap-2">
                <Plus size={18}/> <span>Post Ad</span>
            </Link>

            {!user ? (
              <div className="flex items-center gap-4 text-sm font-bold">
                <Link href="/login" className="text-gray-600 hover:text-indigo-600">Login</Link>
                <Link href="/register" className="text-indigo-600 bg-indigo-50 px-5 py-2.5 rounded-full">Register</Link>
              </div>
            ) : (
              <div className="relative">
                <button onClick={() => setMenuOpen(!menuOpen)} className="flex items-center gap-2 font-bold text-sm text-slate-700">
                   <User size={20} /> {user.name}
                </button>
                {menuOpen && (
                   <div className="absolute right-0 top-full mt-3 w-48 bg-white border border-gray-100 rounded-xl shadow-xl py-2 z-50">
                      <Link href="/bana-ozel" className="block px-4 py-2 hover:bg-gray-50 text-sm">Dashboard</Link>
                      <Link href="/bana-ozel/ilanlarim" className="block px-4 py-2 hover:bg-gray-50 text-sm">My Ads</Link>
                      <button onClick={logout} className="w-full text-left px-4 py-2 hover:bg-red-50 text-sm text-red-600">Logout</button>
                   </div>
                )}
              </div>
            )}
        </div>
      </div>
    </header>
  );
}
`;

// ---------------------------------------------------------
// 9. FOOTER (components/Footer.tsx)
// ---------------------------------------------------------
const footerContent = `
import React from 'react';
import Link from 'next/link';

export default function Footer() {
  return (
    <footer className="mt-10 border-t border-gray-200 bg-white text-xs text-gray-600">
      <div className="container mx-auto px-4 max-w-[1150px] py-8">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
          <div>
            <h4 className="font-bold text-[#333] mb-3 text-sm">Corporate</h4>
            <ul className="space-y-2">
              <li><Link href="#" className="hover:underline">About Us</Link></li>
              <li><Link href="#" className="hover:underline">Careers</Link></li>
              <li><Link href="#" className="hover:underline">Contact</Link></li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold text-[#333] mb-3 text-sm">Services</h4>
            <ul className="space-y-2">
              <li><Link href="#" className="hover:underline">Secure Payment</Link></li>
              <li><Link href="#" className="hover:underline">Advertise</Link></li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold text-[#333] mb-3 text-sm">Privacy</h4>
            <ul className="space-y-2">
              <li><Link href="#" className="hover:underline">Terms of Use</Link></li>
              <li><Link href="#" className="hover:underline">Privacy Policy</Link></li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold text-[#333] mb-3 text-sm">Follow Us</h4>
            <p>Support: <span className="font-bold text-[#333]">support@electronicusa.com</span></p>
          </div>
        </div>
      </div>
      <div className="border-t border-gray-200 bg-[#f6f7f9] py-6 text-center">
        <p>Copyright © 2026 ElectronicUSA. All rights reserved.</p>
      </div>
    </footer>
  );
}
`;

// ---------------------------------------------------------
// 10. SUCCESS PAGE (app/ilan-ver/basarili/page.tsx)
// ---------------------------------------------------------
const successPageContent = `
import React from 'react';
import Link from 'next/link';
import { CheckCircle, Home, Eye } from 'lucide-react';

export default function PostAdSuccess() {
  return (
    <div className="flex flex-col items-center justify-center py-20 text-center px-4">
      <div className="w-24 h-24 bg-green-100 rounded-full flex items-center justify-center text-green-600 mb-6">
        <CheckCircle size={56} />
      </div>

      <h1 className="text-3xl font-black text-gray-900 mb-3">Congratulations!</h1>
      <h2 className="text-xl font-medium text-gray-600 mb-8">Your ad has been created successfully.</h2>

      <div className="flex gap-4">
        <Link href="/" className="flex items-center gap-2 px-6 py-3 bg-gray-100 text-gray-700 font-bold rounded-xl hover:bg-gray-200">
          <Home size={20} /> Home
        </Link>
        <Link href="/bana-ozel/ilanlarim" className="flex items-center gap-2 px-6 py-3 bg-indigo-600 text-white font-bold rounded-xl hover:bg-indigo-700">
          <Eye size={20} /> Manage Ads
        </Link>
      </div>
    </div>
  );
}
`;

// ---------------------------------------------------------
// 11. LAYOUT (app/ilan-ver/layout.tsx)
// ---------------------------------------------------------
const layoutContent = `
"use client";
import React from 'react';
import { usePathname } from 'next/navigation';
import { Check, Layers, FileText } from 'lucide-react';

const steps = [
  { id: 'category', label: 'Category', path: '/ilan-ver', icon: Layers },
  { id: 'details', label: 'Details', path: '/ilan-ver/detay', icon: FileText },
];

export default function PostAdLayout({ children }) {
  const pathname = usePathname();
  const activeIndex = steps.findIndex(s => pathname === s.path || pathname.startsWith(s.path + '/'));
  const safeActiveIndex = activeIndex === -1 && pathname.includes('basarili') ? 2 : activeIndex;

  return (
    <div className="min-h-screen bg-gray-50/50 pb-20">
      <div className="bg-white border-b border-gray-200 sticky top-0 z-40">
        <div className="container max-w-5xl mx-auto px-4 py-4 flex justify-between items-center">
            {steps.map((step, idx) => (
                <div key={step.id} className="flex items-center gap-2">
                    <div className={\`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold \${idx <= safeActiveIndex ? 'bg-indigo-600 text-white' : 'bg-gray-200 text-gray-500'}\`}>
                        {idx + 1}
                    </div>
                    <span className="font-bold text-sm text-gray-700 hidden md:block">{step.label}</span>
                </div>
            ))}
        </div>
      </div>
      <main className="container max-w-5xl mx-auto px-4 py-8">
        {children}
      </main>
    </div>
  );
}
`;

// ---------------------------------------------------------
// 12. CATEGORY WIZARD (components/CategoryWizard.tsx)
// ---------------------------------------------------------
const categoryWizardContent = `
"use client";
import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ChevronRight, ArrowLeft, Monitor, Smartphone, Camera, Tv, Gamepad2, Plug, CheckCircle2, Laptop } from 'lucide-react';
import { categoryTree, computerBrands, phoneBrands } from '@/lib/hierarchyData';

const iconMap = {
  Monitor: <Monitor size={28} />,
  Smartphone: <Smartphone size={28} />,
  Camera: <Camera size={28} />,
  Tv: <Tv size={28} />,
  Gamepad2: <Gamepad2 size={28} />,
  Plug: <Plug size={28} />,
  Laptop: <Laptop size={28} />
};

export default function CategoryWizard() {
  const router = useRouter();
  const [history, setHistory] = useState([]);
  const [currentList, setCurrentList] = useState(categoryTree);
  const [selectedPath, setSelectedPath] = useState([]);
  const [isBrandSelection, setIsBrandSelection] = useState(false);

  const handleSelect = (item) => {
    if (item.isDynamic) {
        setIsBrandSelection(true);
        setHistory([...history, currentList]);
        setSelectedPath([...selectedPath, item.title]);

        let brands = [];
        if (item.dynamicType === 'computer') brands = computerBrands;
        if (item.dynamicType === 'phone') brands = phoneBrands;

        const brandList = brands.map(brand => ({
            id: brand,
            title: brand,
            slug: brand.toLowerCase().replace(/ /g, '-'),
            isFinal: true
        }));
        setCurrentList(brandList);
        return;
    }

    if (isBrandSelection) {
        const brand = item.title;
        const finalPath = [...selectedPath, brand].join(' > ');
        router.push(\`/ilan-ver/detay?cat=\${selectedPath[0]?.toLowerCase().includes('computing') ? 'laptops' : 'smartphones'}&path=\${encodeURIComponent(finalPath)}&brand=\${encodeURIComponent(brand)}\`);
        return;
    }

    const newPath = [...selectedPath, item.title];

    if (item.subs && item.subs.length > 0) {
      setHistory([...history, currentList]);
      setCurrentList(item.subs);
      setSelectedPath(newPath);
    } else {
      router.push(\`/ilan-ver/detay?cat=\${item.slug}&path=\${newPath.join(' > ')}\`);
    }
  };

  const handleBack = () => {
    if (history.length === 0) return;
    const prevList = history[history.length - 1];
    setHistory(history.slice(0, -1));
    setCurrentList(prevList);
    setSelectedPath(selectedPath.slice(0, -1));
    if (isBrandSelection) setIsBrandSelection(false);
  };

  return (
    <div className="w-full">
      <div className="flex items-center gap-4 mb-6">
        {history.length > 0 && (
          <button onClick={handleBack} className="w-10 h-10 rounded-full bg-white border border-gray-200 flex items-center justify-center text-gray-600 hover:bg-indigo-50 hover:text-indigo-600 transition-all shadow-sm">
            <ArrowLeft size={20} />
          </button>
        )}
        <div>
          <h2 className="text-xl font-bold text-slate-900">
            {history.length === 0 ? 'Select Category' : selectedPath[selectedPath.length - 1] || 'Make a selection'}
          </h2>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {currentList.map((item) => {
          const Icon = iconMap[item.icon] || null;
          const isLeaf = (!item.subs || item.subs.length === 0) || item.isFinal;

          return (
            <button
              key={item.id || item.title}
              onClick={() => handleSelect(item)}
              className="group relative flex items-center p-5 bg-white border border-gray-200 rounded-xl hover:border-indigo-500 hover:shadow-md transition-all duration-200 text-left"
            >
              <div className="w-14 h-14 rounded-lg flex items-center justify-center mr-4 bg-gray-100 text-gray-500 group-hover:bg-indigo-100 group-hover:text-indigo-700">
                {history.length === 0 && Icon ? Icon : (isLeaf ? <CheckCircle2 size={24} className="text-green-600" /> : <div className="text-sm font-bold opacity-50">{item.title.substring(0,2).toUpperCase()}</div>)}
              </div>
              <div className="flex-1 min-w-0">
                <span className="block font-bold text-slate-700 group-hover:text-indigo-900 text-base mb-0.5 truncate">{item.title}</span>
                <span className="text-xs text-slate-400 group-hover:text-indigo-500 font-medium">
                    {isLeaf ? 'Select' : 'View Subcategories'}
                </span>
              </div>
            </button>
          );
        })}
      </div>
    </div>
  );
}
`;

// ---------------------------------------------------------
// 13. AD FEATURES (components/AdDetail/FeaturesTab.tsx)
// ---------------------------------------------------------
const featuresTabContent = `
import React from 'react';

export default function FeaturesTab({ ad }) {
  const renderRow = (label, value) => {
    if (value === null || value === undefined || value === '') return null;
    return (
       <div className="flex justify-between border-b border-gray-100 py-3 text-sm hover:bg-gray-50 px-2 transition-colors last:border-0">
          <span className="font-semibold text-gray-600 w-1/2">{label}</span>
          <span className="text-gray-900 font-bold w-1/2 text-right">{value}</span>
       </div>
    );
  };

  return (
    <div className="bg-white border border-gray-200 rounded-lg p-4 shadow-sm">
       <h4 className="font-bold text-gray-800 text-sm uppercase tracking-wider mb-4 border-b pb-2">Technical Specifications</h4>
       <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-1">
          {renderRow('Brand', ad.brand)}
          {renderRow('Model', ad.model)}
          {renderRow('Processor', ad.processor)}
          {renderRow('RAM', ad.ram)}
          {renderRow('Screen Size', ad.screen_size)}
          {renderRow('Graphics', ad.gpu_capacity)}
          {renderRow('Storage', ad.ssd_capacity)}
          {renderRow('Resolution', ad.resolution)}
          {renderRow('Category', ad.category)}
       </div>
    </div>
  );
}
`;

// ---------------------------------------------------------
// 14. HOME PAGE (app/page.tsx)
// ---------------------------------------------------------
const homePageContent = `
import React from 'react';
import Sidebar from "@/components/Sidebar";
import HomeFeed from "@/components/HomeFeed";
import { getInfiniteAdsAction, getCategoryTreeServer } from "@/lib/actions";

export const revalidate = 0;

export default async function Home() {
  const { data: initialAds } = await getInfiniteAdsAction(1, 20);
  const categories = await getCategoryTreeServer();

  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        <aside className="hidden lg:block lg:col-span-3 xl:col-span-2">
          <div className="sticky top-24">
            <Sidebar categories={categories} />
          </div>
        </aside>
        <main className="lg:col-span-9 xl:col-span-10 min-w-0">
          <HomeFeed initialAds={initialAds} />
        </main>
      </div>
    </div>
  );
}
`;

// ---------------------------------------------------------
// 15. COMPUTER FIELDS (components/form/ComputerFields.tsx)
// ---------------------------------------------------------
const computerFieldsContent = `
import React from 'react';
import { processors, ramOptions, screenSizes, gpuCapacities, resolutions, ssdCapacities } from '@/lib/computerData';

export default function ComputerFields({ data, onChange, categorySlug }) {
  const handleChange = (e) => { onChange(e); };
  const isPhone = categorySlug?.includes('phone') || categorySlug?.includes('smart');

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div>
        <label className="block text-[12px] font-bold text-gray-600 mb-1">Processor</label>
        <select name="processor" value={data.processor || ''} onChange={handleChange} className="w-full border border-gray-300 rounded-sm h-10 px-2 text-sm bg-white outline-none">
          <option value="">Select</option>
          {processors.map(p => <option key={p} value={p}>{p}</option>)}
        </select>
      </div>

      <div>
        <label className="block text-[12px] font-bold text-gray-600 mb-1">RAM</label>
        <select name="ram" value={data.ram || ''} onChange={handleChange} className="w-full border border-gray-300 rounded-sm h-10 px-2 text-sm bg-white outline-none">
          <option value="">Select</option>
          {ramOptions.map(r => <option key={r} value={r}>{r}</option>)}
        </select>
      </div>

      <div>
        <label className="block text-[12px] font-bold text-gray-600 mb-1">Storage</label>
        <select name="ssd_capacity" value={data.ssd_capacity || ''} onChange={handleChange} className="w-full border border-gray-300 rounded-sm h-10 px-2 text-sm bg-white outline-none">
          <option value="">Select</option>
          {ssdCapacities.map(s => <option key={s} value={s}>{s}</option>)}
        </select>
      </div>

      {!isPhone && (
        <div>
            <label className="block text-[12px] font-bold text-gray-600 mb-1">Graphics Card</label>
            <select name="gpu_capacity" value={data.gpu_capacity || ''} onChange={handleChange} className="w-full border border-gray-300 rounded-sm h-10 px-2 text-sm bg-white outline-none">
            <option value="">Select</option>
            {gpuCapacities.map(g => <option key={g} value={g}>{g}</option>)}
            </select>
        </div>
      )}

      <div>
        <label className="block text-[12px] font-bold text-gray-600 mb-1">Screen Size</label>
        <select name="screen_size" value={data.screen_size || ''} onChange={handleChange} className="w-full border border-gray-300 rounded-sm h-10 px-2 text-sm bg-white outline-none">
          <option value="">Select</option>
          {screenSizes.map(s => <option key={s} value={s}>{s}</option>)}
        </select>
      </div>

      <div>
        <label className="block text-[12px] font-bold text-gray-600 mb-1">Resolution</label>
        <select name="resolution" value={data.resolution || ''} onChange={handleChange} className="w-full border border-gray-300 rounded-sm h-10 px-2 text-sm bg-white outline-none">
          <option value="">Select</option>
          {resolutions.map(r => <option key={r} value={r}>{r}</option>)}
        </select>
      </div>
    </div>
  );
}
`;

// Files to Write
const filesToWrite = [
  { path: "supabase/migration_english.sql", content: sqlContent },
  { path: "lib/data.ts", content: dataTsContent },
  { path: "lib/hierarchyData.ts", content: hierarchyDataContent },
  { path: "lib/schemas.ts", content: schemaContent },
  { path: "lib/locations.ts", content: locationsContent },
  { path: "components/FilterSidebar.tsx", content: filterSidebarContent },
  { path: "app/ilan-ver/detay/page.tsx", content: postAdPageContent },
  { path: "components/AdDetail/FeaturesTab.tsx", content: featuresTabContent },
  { path: "components/CategoryWizard.tsx", content: categoryWizardContent },
  { path: "components/Header.tsx", content: headerContent },
  { path: "components/Footer.tsx", content: footerContent },
  { path: "app/ilan-ver/basarili/page.tsx", content: successPageContent },
  { path: "app/ilan-ver/layout.tsx", content: layoutContent },
  { path: "app/page.tsx", content: homePageContent },
  {
    path: "components/form/ComputerFields.tsx",
    content: computerFieldsContent,
  },
];

filesToWrite.forEach((file) => {
  try {
    const dir = path.dirname(file.path);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(process.cwd(), file.path), file.content.trim());
    console.log(colors.green + "✔ " + file.path + " updated." + colors.reset);
  } catch (e) {
    console.error(
      colors.yellow + "✘ " + file.path + " failed: " + e.message + colors.reset,
    );
  }
});

console.log(
  colors.blue +
    colors.bold +
    "\n✅ ENGLISH CONVERSION COMPLETE!" +
    colors.reset,
);
console.log(
  "👉 Step 1: Run 'supabase/migration_english.sql' in Supabase SQL Editor.",
);
console.log("👉 Step 2: Restart your project (npm run dev).");
