const fs = require("fs");
const path = require("path");

const colors = {
  reset: "\x1b[0m",
  green: "\x1b[32m",
  blue: "\x1b[34m",
  yellow: "\x1b[33m",
  bold: "\x1b[1m",
};

console.log(
  colors.blue +
    colors.bold +
    "\n🇺🇸  STARTING FULL ENGLISH CONVERSION (FINAL FIX)...\n" +
    colors.reset,
);

// ---------------------------------------------------------
// 1. SQL MIGRATION (Veritabanını Zorla İngilizce Yap)
// ---------------------------------------------------------
const sqlContent = `
-- ⚠️ BU KODU SUPABASE SQL EDITOR'DE CALISTIRIN ⚠️

-- 1. Tabloları Temizle (Eski Türkçe verileri sil)
TRUNCATE TABLE categories CASCADE;
ALTER TABLE categories ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 2. Ana Kategorileri İngilizce Ekle
INSERT INTO categories (id, title, slug, icon, parent_id) VALUES
(1, 'Computing', 'computing', 'Monitor', NULL),
(2, 'Phones & Accessories', 'phones', 'Smartphone', NULL),
(3, 'Gaming & Consoles', 'gaming', 'Gamepad2', NULL),
(4, 'TV & Audio', 'audio-video', 'Tv', NULL),
(5, 'Cameras & Drones', 'cameras', 'Camera', NULL),
(6, 'Smart Home', 'smart-home', 'Zap', NULL);

-- 3. Sayacı Güncelle
SELECT setval(pg_get_serial_sequence('categories', 'id'), (SELECT MAX(id) FROM categories));

-- 4. Alt Kategorileri İngilizce Ekle
INSERT INTO categories (title, slug, icon, parent_id) VALUES
('Laptops', 'laptops', 'Laptop', 1),
('Desktops', 'desktops', 'Monitor', 1),
('Tablets', 'tablets', 'Tablet', 1),
('Components', 'components', 'Cpu', 1),
('Networking', 'networking', 'Wifi', 1),

('Smartphones', 'smartphones', 'Smartphone', 2),
('Smart Watches', 'wearables', 'Watch', 2),
('Cases & Protection', 'cases', 'Shield', 2),

('Consoles', 'consoles', 'Gamepad', 3),
('Video Games', 'games', 'Disc', 3),
('Accessories', 'gaming-accessories', 'Keyboard', 3),

('Televisions', 'tvs', 'Tv', 4),
('Headphones', 'headphones', 'Headphones', 4),
('Speakers', 'speakers', 'Speaker', 4),

('Digital Cameras', 'digital-cameras', 'Camera', 5),
('Drones', 'drones', 'Plane', 5),

('Robot Vacuums', 'robot-vacuums', 'Bot', 6),
('Smart Lighting', 'smart-lighting', 'Zap', 6);
`;

// ---------------------------------------------------------
// 2. FRONTEND DATA (lib/data.ts) - Tamamen İngilizce
// ---------------------------------------------------------
const dataTsContent = `
import { Monitor, Smartphone, Camera, Tv, Gamepad2, Plug, Cpu, Laptop, Watch, Headphones, Speaker, Shield, Zap, Wifi, Disc, Keyboard, Mouse, Bot, Plane } from 'lucide-react';

export const categories = [
  {
    id: 'computing', title: 'Computing', icon: 'Monitor', slug: 'computing',
    subs: [
      { id: 'laptops', title: 'Laptops', slug: 'laptops', icon: 'Laptop' },
      { id: 'desktops', title: 'Desktops', slug: 'desktops', icon: 'Monitor' },
      { id: 'tablets', title: 'Tablets', slug: 'tablets', icon: 'Tablet' },
      { id: 'components', title: 'Components', slug: 'components', icon: 'Cpu' },
      { id: 'networking', title: 'Networking', slug: 'networking', icon: 'Wifi' }
    ]
  },
  {
    id: 'phones', title: 'Phones & Accessories', icon: 'Smartphone', slug: 'phones',
    subs: [
      { id: 'smartphones', title: 'Smartphones', slug: 'smartphones', icon: 'Smartphone' },
      { id: 'wearables', title: 'Smart Watches', slug: 'wearables', icon: 'Watch' },
      { id: 'cases', title: 'Cases & Protection', slug: 'cases', icon: 'Shield' }
    ]
  },
  {
    id: 'gaming', title: 'Gaming', icon: 'Gamepad2', slug: 'gaming',
    subs: [
      { id: 'consoles', title: 'Consoles', slug: 'consoles', icon: 'Gamepad2' },
      { id: 'games', title: 'Video Games', slug: 'games', icon: 'Disc' },
      { id: 'accessories', title: 'Accessories', slug: 'gaming-accessories', icon: 'Keyboard' }
    ]
  },
  {
    id: 'audio', title: 'TV & Audio', icon: 'Tv', slug: 'audio-video',
    subs: [
      { id: 'tvs', title: 'Televisions', slug: 'tvs', icon: 'Tv' },
      { id: 'headphones', title: 'Headphones', slug: 'headphones', icon: 'Headphones' },
      { id: 'speakers', title: 'Speakers', slug: 'speakers', icon: 'Speaker' }
    ]
  },
  {
    id: 'cameras', title: 'Cameras', icon: 'Camera', slug: 'cameras',
    subs: [
      { id: 'digital', title: 'Digital Cameras', slug: 'digital-cameras', icon: 'Camera' },
      { id: 'drones', title: 'Drones', slug: 'drones', icon: 'Plane' }
    ]
  },
  {
    id: 'smart-home', title: 'Smart Home', icon: 'Zap', slug: 'smart-home',
    subs: [
        { id: 'robot', title: 'Robot Vacuums', slug: 'robot-vacuums', icon: 'Bot' }
    ]
  }
];

export const cities = ['New York', 'California', 'Texas', 'Florida', 'Illinois', 'Washington', 'Nevada', 'Massachusetts'];
`;

// ---------------------------------------------------------
// 3. SIDEBAR (components/Sidebar.tsx)
// ---------------------------------------------------------
const sidebarContent = `
"use client";
import React from 'react';
import Link from 'next/link';
import { Home, Car, Monitor, Briefcase, Shirt, BookOpen, Dog, Hammer, ChevronRight, Smartphone, Gamepad2, Tv, Camera, Zap } from 'lucide-react';
import RecentAdsWidget from '@/components/RecentAdsWidget';

const iconMap: any = { Home, Car, Monitor, Briefcase, Shirt, BookOpen, Dog, Hammer, Smartphone, Gamepad2, Tv, Camera, Zap };

export default function Sidebar({ categories }: { categories: any[] }) {
  return (
    <div className="space-y-6">
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <div className="p-4 border-b border-gray-50 bg-gray-50/50">
          <h3 className="font-bold text-gray-800 text-sm">Categories</h3>
        </div>
        <ul className="divide-y divide-gray-50">
          {categories.map((cat) => {
            const IconComponent = iconMap[cat.icon] || Home;
            return (
              <li key={cat.id} className="group relative">
                <Link href={\`/search?category=\${cat.slug}\`} className="flex items-center justify-between px-4 py-3 text-sm text-gray-600 hover:text-indigo-600 hover:bg-indigo-50/50 transition-all duration-200">
                  <span className="flex items-center gap-3 font-medium">
                    <IconComponent size={16} className="text-gray-400 group-hover:text-indigo-500 transition-colors" />
                    {cat.title}
                  </span>
                  <ChevronRight size={14} className="text-gray-300 group-hover:text-indigo-400 opacity-50 group-hover:opacity-100 transition-all" />
                </Link>

                {/* Mega Menu */}
                {cat.subs && cat.subs.length > 0 && (
                  <div className="hidden group-hover:block absolute left-[100%] top-0 w-64 bg-white border border-gray-100 shadow-xl rounded-r-xl p-4 z-50 ml-2 animate-in fade-in slide-in-from-left-2 duration-200">
                    <h4 className="font-bold text-gray-800 mb-3 pb-2 border-b border-gray-100">{cat.title}</h4>
                    <div className="flex flex-col gap-1">
                      {cat.subs.map((sub: any) => (
                        <Link key={sub.id} href={\`/search?category=\${sub.slug}\`} className="text-sm text-gray-500 hover:text-indigo-600 hover:bg-gray-50 px-2 py-1.5 rounded-md transition-colors">
                          {sub.title}
                        </Link>
                      ))}
                    </div>
                  </div>
                )}
              </li>
            );
          })}
        </ul>
      </div>

      <RecentAdsWidget />

      {/* Ad Space */}
      <div className="h-[250px] bg-gradient-to-br from-gray-100 to-gray-200 rounded-xl flex items-center justify-center border border-gray-200 border-dashed">
        <span className="text-xs font-bold text-gray-400 uppercase tracking-widest">Ad Space</span>
      </div>
    </div>
  );
}
`;

// ---------------------------------------------------------
// 4. HOME FEED (components/HomeFeed.tsx)
// ---------------------------------------------------------
const homeFeedContent = `
"use client";
import React, { useState } from 'react';
import AdCard from '@/components/AdCard';
import { getInfiniteAdsAction } from '@/lib/actions';
import { Loader2, ArrowDown, SearchX, PlusCircle } from 'lucide-react';
import Link from 'next/link';

export default function HomeFeed({ initialAds }: { initialAds: any[] }) {
  const [ads, setAds] = useState<any[]>(initialAds || []);
  const [page, setPage] = useState(2);
  const [hasMore, setHasMore] = useState(true);
  const [loading, setLoading] = useState(false);

  const loadMore = async () => {
    if (loading || !hasMore) return;
    setLoading(true);
    try {
      const res = await getInfiniteAdsAction(page);
      if (res.data && res.data.length > 0) {
        setAds(prev => [...prev, ...res.data]);
        setPage(prev => prev + 1);
        setHasMore(res.hasMore);
      } else {
        setHasMore(false);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  // EMPTY STATE
  if (!ads || ads.length === 0) {
      return (
          <div className="flex flex-col items-center justify-center py-20 bg-white border border-gray-100 rounded-xl shadow-sm text-center">
              <div className="bg-blue-50 p-6 rounded-full mb-6 animate-in zoom-in duration-300">
                  <SearchX size={48} className="text-blue-600" />
              </div>
              <h2 className="text-2xl font-bold text-gray-800 mb-2">No Active Ads Yet</h2>
              <p className="text-gray-500 max-w-md mb-8">
                  There are no ads to display in the showcase right now. Be the first to reach thousands of buyers!
              </p>
              <Link
                  href="/ilan-ver"
                  className="bg-indigo-600 text-white px-8 py-4 rounded-xl font-bold hover:bg-indigo-700 transition-all shadow-lg hover:shadow-indigo-200 flex items-center gap-2"
              >
                  <PlusCircle size={20} /> Post Free Ad
              </Link>
          </div>
      );
  }

  return (
    <div className="space-y-6">
      {/* Showcase Header */}
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold text-gray-800 flex items-center gap-2">
          <span className="w-2 h-8 bg-indigo-600 rounded-full"></span>
          Showcase Ads
        </h2>
        <span className="text-xs font-medium text-gray-500 bg-gray-100 px-3 py-1 rounded-full">{ads.length} Ads</span>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 gap-3 md:gap-6">
        {ads.map((ad) => (
          <div key={ad.id} className="h-full animate-in fade-in zoom-in-95 duration-500">
            <AdCard ad={ad} viewMode="grid" />
          </div>
        ))}
      </div>

      {/* Load More Button */}
      {hasMore && (
        <div className="pt-8 text-center">
          <button
            onClick={loadMore}
            disabled={loading}
            className="group relative inline-flex items-center justify-center px-8 py-3 text-sm font-bold text-indigo-600 transition-all duration-200 bg-white border-2 border-indigo-50 rounded-full hover:bg-indigo-50 hover:border-indigo-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-600 disabled:opacity-50"
          >
            {loading ? <Loader2 className="animate-spin mr-2" size={18}/> : <ArrowDown className="mr-2 group-hover:translate-y-1 transition-transform" size={18}/>}
            {loading ? 'Loading...' : 'Load More'}
          </button>
        </div>
      )}
    </div>
  );
}
`;

// ---------------------------------------------------------
// 5. RECENT ADS WIDGET (components/RecentAdsWidget.tsx)
// ---------------------------------------------------------
const recentAdsContent = `
"use client";
import React from 'react';
import Link from 'next/link';
import { useHistory } from '@/context/HistoryContext';
import { History, Trash2 } from 'lucide-react';

export default function RecentAdsWidget() {
  const { recentAds, clearHistory } = useHistory();

  if (!recentAds || recentAds.length === 0) return null;

  return (
    <div className="mt-4 bg-white border border-gray-200 rounded-sm shadow-sm overflow-hidden">
      <div className="bg-gray-50 p-3 border-b border-gray-100 flex justify-between items-center">
        <h3 className="text-xs font-bold text-[#333] flex items-center gap-1">
          <History size={14} className="text-blue-600" />
          Recently Viewed
        </h3>
        <button onClick={clearHistory} className="text-gray-400 hover:text-red-500" title="Clear">
          <Trash2 size={12} />
        </button>
      </div>

      <ul>
        {recentAds.map((ad) => (
          <li key={ad.id} className="border-b border-gray-50 last:border-0">
            <Link href={\`/ilan/\${ad.id}\`} className="flex gap-2 p-2 hover:bg-blue-50 transition-colors group">
              <div className="w-12 h-10 bg-gray-200 shrink-0 overflow-hidden rounded-sm border border-gray-200">
                <img src={ad.image} alt={ad.title} className="w-full h-full object-cover group-hover:scale-110 transition-transform" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-[10px] font-semibold text-[#333] truncate group-hover:text-blue-700">{ad.title}</p>
                <p className="text-[10px] font-bold text-blue-900">{ad.price} {ad.currency}</p>
              </div>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}
`;

// ---------------------------------------------------------
// 6. SMART CATEGORY GRID (components/SmartCategoryGrid.tsx)
// ---------------------------------------------------------
const smartGridContent = `
"use client";
import React from 'react';
import Link from 'next/link';
import { ChevronRight, LayoutGrid, List } from 'lucide-react';
import { categoryTree, computerBrands } from '@/lib/hierarchyData';

function findCategoryBySlug(cats: any[], slug: string): any {
  for (const cat of cats) {
    if (cat.slug === slug) return cat;
    if (cat.subs) {
      const found = findCategoryBySlug(cat.subs, slug);
      if (found) return found;
    }
  }
  return null;
}

export default function SmartCategoryGrid({ searchParams }: { searchParams: any }) {
  const currentSlug = searchParams.category;
  const currentBrand = searchParams.brand;

  const categoryNode = currentSlug ? findCategoryBySlug(categoryTree, currentSlug) : null;

  if (!categoryNode) {
    return <GridDisplay items={categoryTree} type="category" parentParams={searchParams} title="Categories" />;
  }

  if (categoryNode.subs && categoryNode.subs.length > 0) {
    return (
        <GridDisplay
            items={categoryNode.subs}
            type="category"
            parentParams={searchParams}
            title={\`\${categoryNode.title} Subcategories\`}
            listAllLabel={\`List All \${categoryNode.title} Ads\`}
        />
    );
  }

  if (categoryNode.isDynamic) {
      if (!currentBrand) {
          const brands = computerBrands.sort().map(b => ({ id: b, title: b, slug: b.toLowerCase() }));
          return (
            <GridDisplay
                items={brands}
                type="brand"
                parentParams={searchParams}
                title="Select Brand"
                listAllLabel="List All Ads"
            />
          );
      }
  }

  return null;
}

function GridDisplay({ items, type, parentParams, title, listAllLabel }: any) {
  const listAllParams = new URLSearchParams(parentParams);
  listAllParams.set('showResults', 'true');

  return (
    <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm mb-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex flex-col md:flex-row md:items-center justify-between mb-6 gap-4">
        <h2 className="text-xl font-bold text-gray-800 flex items-center gap-2">
          <LayoutGrid className="text-indigo-600" size={24} />
          {title}
        </h2>

        {listAllLabel && (
            <Link
                href={\`/search?\${listAllParams.toString()}\`}
                className="bg-slate-800 text-white px-5 py-2.5 rounded-lg text-sm font-bold hover:bg-slate-700 transition-all shadow-md hover:shadow-lg flex items-center justify-center gap-2 group"
            >
                <List size={16} className="text-slate-300 group-hover:text-white" />
                {listAllLabel}
            </Link>
        )}
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-4">
        {items.map((item: any) => {
          const params = new URLSearchParams(parentParams);
          if (type === 'category') params.set('category', item.slug);
          else if (type === 'brand') params.set('brand', item.title);

          return (
            <Link
              key={item.id}
              href={\`/search?\${params.toString()}\`}
              className="flex flex-col items-center justify-center p-4 border border-gray-100 rounded-xl hover:border-indigo-500 hover:bg-indigo-50 hover:shadow-lg transition-all group text-center h-28 relative overflow-hidden"
            >
              <div className="absolute top-0 right-0 p-2 opacity-0 group-hover:opacity-100 transition-opacity">
                <ChevronRight size={16} className="text-indigo-600" />
              </div>
              <div className="w-10 h-10 bg-gray-100 rounded-full flex items-center justify-center mb-2 group-hover:bg-white group-hover:text-indigo-600 transition-colors text-gray-500 font-bold text-lg shadow-sm">
                {item.title.charAt(0).toUpperCase()}
              </div>
              <span className="font-bold text-gray-700 text-sm group-hover:text-indigo-700 line-clamp-2 leading-tight">
                {item.title}
              </span>
            </Link>
          );
        })}
      </div>
    </div>
  );
}
`;

// ---------------------------------------------------------
// 7. HIERARCHY DATA (lib/hierarchyData.ts)
// ---------------------------------------------------------
const hierarchyDataContent = `
import { Monitor, Smartphone, Camera, Tv, Gamepad2 } from 'lucide-react';

export type CategoryNode = {
  id: string;
  title: string;
  slug: string;
  icon?: any;
  subs?: CategoryNode[];
  isDynamic?: boolean;
  dynamicType?: 'computer' | 'phone';
};

export const categoryTree: CategoryNode[] = [
  {
    id: 'computing', title: 'Computing', icon: 'Monitor', slug: 'computing',
    subs: [
      { id: 'laptops', title: 'Laptops', slug: 'laptops', isDynamic: true, dynamicType: 'computer' },
      { id: 'desktops', title: 'Desktops', slug: 'desktops' },
      { id: 'tablets', title: 'Tablets', slug: 'tablets' },
      { id: 'components', title: 'Components', slug: 'components' }
    ]
  },
  {
    id: 'phones', title: 'Phones', icon: 'Smartphone', slug: 'phones',
    subs: [
      { id: 'smartphones', title: 'Smartphones', slug: 'smartphones', isDynamic: true, dynamicType: 'phone' },
      { id: 'accessories', title: 'Accessories', slug: 'cases' }
    ]
  },
  {
    id: 'gaming', title: 'Gaming', icon: 'Gamepad2', slug: 'gaming',
    subs: [
      { id: 'consoles', title: 'Consoles', slug: 'consoles' }
    ]
  }
];

export const carHierarchy: Record<string, Record<string, string[]>> = {};

export const computerBrands = [
  "Apple", "Dell", "HP", "Lenovo", "Asus", "Acer", "MSI", "Razer", "Microsoft", "Samsung", "Toshiba"
];

export const phoneBrands = [
  "Apple", "Samsung", "Google", "OnePlus", "Motorola", "Xiaomi", "Sony", "Nokia"
];
`;

// Dosyaları yazma işlemi
const filesToWrite = [
  { path: "supabase/force_english.sql", content: sqlContent },
  { path: "lib/data.ts", content: dataTsContent },
  { path: "lib/hierarchyData.ts", content: hierarchyDataContent },
  { path: "components/Sidebar.tsx", content: sidebarContent },
  { path: "components/HomeFeed.tsx", content: homeFeedContent },
  { path: "components/RecentAdsWidget.tsx", content: recentAdsContent },
  { path: "components/SmartCategoryGrid.tsx", content: smartGridContent },
];

filesToWrite.forEach((file) => {
  try {
    const dir = path.dirname(file.path);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    fs.writeFileSync(path.join(process.cwd(), file.path), file.content.trim());
    console.log(colors.green + "✔ " + file.path + " updated." + colors.reset);
  } catch (e) {
    console.error(
      colors.yellow + "✘ " + file.path + " failed: " + e.message + colors.reset,
    );
  }
});

console.log(colors.blue + colors.bold + "\n✅ FILES UPDATED!" + colors.reset);
console.log(
  "👉 IMPORTANT: Run 'supabase/force_english.sql' in Supabase SQL Editor to remove Turkish categories.",
);
console.log("👉 Restart with 'npm run dev' to see changes.");
